/**
 * The `arcturn serve` browser client, as one self-contained HTML document.
 *
 * ## Why a string, not a file
 *
 * The page is generated by {@link renderWebClientPage} and served straight out
 * of memory by `web/server.ts`. Everything it needs — the stylesheet, both
 * halves of the client script, the favicon — is inlined, so:
 *
 * - it ships in `dist/` as ordinary compiled JavaScript, with no bundler, no
 *   asset copy step and no addition to the package's `files` list;
 * - it makes **no external request at all**: no CDN, no web font, no image
 *   host. The only network traffic it originates is the WebSocket back to the
 *   server that served it, which is also all its Content-Security-Policy
 *   permits (see `server.ts`).
 *
 * The static shell below is authored here and is therefore trusted; everything
 * that arrives over the socket is rendered by `script/model.ts` into vnodes and
 * mounted with `textContent` by `script/app.ts`. No server-, model- or
 * tool-authored string is ever concatenated into markup.
 *
 * @packageDocumentation
 */

import { APP_SCRIPT } from "./script/app.js";
import { MODEL_SCRIPT } from "./script/model.js";
import { WEB_CLIENT_CSS } from "./styles.js";

/** Document title, also used as the app name on a phone home screen. */
export const WEB_CLIENT_TITLE = "arcturn";

/** The ✦ mark as an inline SVG data URI — a favicon that costs no request. */
const FAVICON =
  "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E" +
  "%3Crect width='32' height='32' rx='7' fill='%230a0a14'/%3E" +
  "%3Ctext x='16' y='24' font-size='22' font-family='monospace' fill='%23a78bfa' " +
  "text-anchor='middle'%3E%CF%84%3C/text%3E%3C/svg%3E";

/** Options for {@link renderWebClientPage}. */
export interface WebClientPageOptions {
  /**
   * Port the `arcturn serve` WebSocket listener is bound to. The page dials the
   * host it was loaded from on this port, so reaching the page over a LAN
   * address or a tunnel hostname reaches the socket the same way.
   */
  readonly wsPort: number;
  /**
   * Fully-qualified WebSocket URL, overriding the host-relative default.
   * Only needed when the socket is not on the page's own hostname.
   */
  readonly wsUrl?: string;
  /**
   * Content-Security-Policy nonce stamped on the inline `<style>` and
   * `<script>` elements. Supply the same value in the `script-src`/`style-src`
   * directives; omit it only when serving without a CSP.
   */
  readonly nonce?: string;
}

/** Runtime configuration handed to the page as `window.__ARCTURN__`. */
interface PageConfig {
  readonly wsPort: number;
  readonly wsUrl?: string;
}

/** Keep a nonce to the CSP base64 character set, whatever the caller passed. */
function safeNonce(nonce: string | undefined): string {
  if (nonce === undefined) return "";
  return nonce.replace(/[^A-Za-z0-9+/=_-]/g, "");
}

/**
 * Serialize the page config for embedding in a script element. `<` is escaped
 * so no value could ever close the element early.
 */
function embedJson(value: PageConfig): string {
  return JSON.stringify(value).replace(/</g, "\\u003c");
}

/**
 * Render the complete browser-client document.
 *
 * @param options - Where the page should dial, and the CSP nonce to stamp.
 * @returns One self-contained HTML document; no external resources.
 *
 * @example
 * ```ts
 * const html = renderWebClientPage({ wsPort: 7717, nonce });
 * response.end(html);
 * ```
 */
export function renderWebClientPage(options: WebClientPageOptions): string {
  const nonce = safeNonce(options.nonce);
  const attribute = nonce === "" ? "" : ` nonce="${nonce}"`;
  const config: PageConfig =
    options.wsUrl === undefined
      ? { wsPort: options.wsPort }
      : { wsPort: options.wsPort, wsUrl: options.wsUrl };

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover, interactive-widget=resizes-content">
<meta name="color-scheme" content="dark light">
<meta name="theme-color" content="#0a0a14">
<meta name="referrer" content="no-referrer">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="${WEB_CLIENT_TITLE}">
<title>${WEB_CLIENT_TITLE} — web client</title>
<link rel="icon" href="${FAVICON}">
<style${attribute}>${WEB_CLIENT_CSS}</style>
</head>
<body>
<a class="skip" href="#composer-input">Skip to the composer</a>

<header class="top">
  <button type="button" class="brand" id="btn-sessions" aria-label="Sessions" aria-haspopup="dialog">
    <span class="mark" aria-hidden="true">✦</span>arcturn
  </button>
  <div class="top-meta">
    <div class="top-title" id="session-title">no session</div>
    <div class="top-sub" id="session-cwd"></div>
  </div>
  <span class="conn" id="conn" role="status" aria-live="polite" data-state="offline">offline</span>
</header>

<main class="transcript" id="transcript" tabindex="0" role="log" aria-live="polite" aria-relevant="additions text" aria-label="Session transcript"></main>
<div class="live" id="live" aria-label="Streaming reply"></div>
<ul class="todos" id="todos" aria-label="Todos"></ul>
<div class="activity" id="activity" hidden>
  <span class="spin" id="activity-spinner" aria-hidden="true">●</span>
  <span id="activity-text"></span>
</div>

<form class="composer" id="composer" autocomplete="off">
  <textarea id="composer-input" rows="1" placeholder="Message the session…" aria-label="Message the session" autocapitalize="sentences" enterkeyhint="send"></textarea>
  <button type="button" class="danger" id="btn-abort" hidden>Stop</button>
  <button type="submit" class="primary" id="btn-send">Send</button>
</form>

<div class="scrim" id="scrim" hidden></div>

<section class="sheet" id="permission" role="dialog" aria-modal="true" aria-labelledby="permission-title" hidden>
  <h2 id="permission-title"><span class="mark" aria-hidden="true">◆</span> Permission needed</h2>
  <p class="hint">The agent is asking to run this. Read it before you allow it.</p>
  <div class="subject" id="permission-body" tabindex="0" aria-label="Requested action"></div>
  <p class="gate" id="permission-gate" hidden>Scroll to the end of the request before allowing it.</p>
  <div class="actions">
    <button type="button" class="danger" id="perm-deny">Deny</button>
    <button type="button" id="perm-always">Allow always</button>
    <button type="button" class="primary" id="perm-allow">Allow once</button>
  </div>
</section>

<section class="sheet" id="sessions" role="dialog" aria-modal="true" aria-labelledby="sessions-title" hidden>
  <h2 id="sessions-title">Sessions</h2>
  <ul class="sessions" id="sessions-list"></ul>
  <div class="actions">
    <button type="button" class="ghost" id="btn-close-sessions">Close</button>
    <button type="button" class="primary" id="btn-new-session">New session</button>
  </div>
</section>

<section class="sheet" id="token" role="dialog" aria-modal="true" aria-labelledby="token-title" hidden>
  <h2 id="token-title">Access token</h2>
  <p class="hint">arcturn serve printed a token when it started. It is kept for this tab only, never displayed and never logged.</p>
  <form class="token-form" id="token-form">
    <input type="password" id="token-input" name="token" aria-label="Access token" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false">
    <p class="token-error" id="token-error" role="alert" hidden></p>
    <div class="actions">
      <button type="button" class="ghost" id="btn-token-skip">No token</button>
      <button type="submit" class="primary">Connect</button>
    </div>
  </form>
</section>

<script${attribute}>window.__ARCTURN__ = ${embedJson(config)};</script>
<script${attribute}>${MODEL_SCRIPT}</script>
<script${attribute}>${APP_SCRIPT}</script>
</body>
</html>
`;
}
