/** @arcturn/protocol — NDJSON wire-protocol framing and validation for Arcturn server mode. */

export { PROTOCOL_VERSION } from "@arcturn/types";
export {
  ClientErrorCode,
  createProtocolClient,
  isUnsupportedMethodError,
  type ProtocolClient,
  ProtocolClientError,
  type ProtocolClientOptions,
  ProtocolClosedError,
  type ProtocolEventListener,
  ProtocolRequestError,
  ProtocolTimeoutError,
  ProtocolVersionMismatchError,
  type WebSocketLike,
} from "./client.js";
export type { FrameDecoderOptions, ProtocolError } from "./framing.js";
export {
  DEFAULT_MAX_LINE_LENGTH,
  encodeFrame,
  FrameDecoder,
  isProtocolError,
} from "./framing.js";
export { ErrorCode, errorResponse, eventMessage, okResponse, sessionsMessage } from "./messages.js";
export { nextRequestId, RequestIdGenerator } from "./request-id.js";
export type {
  ClientRequestValidation,
  ServerMessageValidation,
  ValidationResult,
} from "./validate.js";
export {
  MAX_BACKGROUND_AGENT_ID_LENGTH,
  MAX_BACKGROUND_TASK_LENGTH,
  MAX_CHANGE_SELECTION,
  MAX_CHECKPOINT_ID_LENGTH,
  MAX_CONTEXT_QUERY_LENGTH,
  MAX_MCP_SERVER_NAME_LENGTH,
  MAX_ORG_MEMORY_FIELD_LENGTH,
  MAX_PENDING_CHANGE_PATH_LENGTH,
  MAX_PROMPT_ATTACHMENTS,
  MAX_WORKFLOW_INPUT_LENGTH,
  MAX_WORKFLOW_NAME_LENGTH,
  MAX_WORKFLOW_RUN_ID_LENGTH,
  validateAdoptBackgroundAgentResult,
  validateApplyChangesResult,
  validateBackgroundAgentList,
  validateBackgroundAgentSummary,
  validateBackgroundAgentTranscript,
  validateCancelBackgroundAgentResult,
  validateCheckpointEntry,
  validateCheckpointList,
  validateClientRequest,
  validateCommandDescriptor,
  validateCommandList,
  validateCompactionSummary,
  validateContextResolution,
  validateDiscardChangesResult,
  validateLineRange,
  validateMcpServerSummary,
  validateMcpStatus,
  validateModelCatalog,
  validateModelCatalogEntry,
  validateModelCost,
  validateOrgMemoryEntry,
  validateOrgMemoryList,
  validateOrgMemoryProposal,
  validatePendingChange,
  validatePendingChanges,
  validatePermissionDecision,
  validatePermissionRule,
  validatePermissionState,
  validatePromptAttachment,
  validateRewindResult,
  validateServerMessage,
  validateSessionExport,
  validateSessionHeader,
  validateSessionHistory,
  validateStartedBackgroundAgent,
  validateWorkflowCatalog,
  validateWorkflowRunHandle,
  validateWorkflowRunStatus,
  validateWorkflowRuns,
  validateWorkflowSummary,
} from "./validate.js";
