/**
 * Client request id generation.
 *
 * Ids are `${randomPrefix}-${monotonicCounter}`: a random prefix generated
 * once (per {@link RequestIdGenerator} instance, or once at module load for
 * {@link nextRequestId}) makes ids generated by independent processes/tabs
 * collision-resistant, while the monotonic counter guarantees uniqueness and
 * generation order within a single process without relying on wall-clock
 * resolution.
 */

const COUNTER_RADIX = 36;

/** Generates monotonic, collision-resistant request ids for one client. */
export class RequestIdGenerator {
  private readonly prefix: string;
  private counter = 0;

  constructor() {
    this.prefix = randomPrefix();
  }

  /** Produce the next request id from this generator. */
  next(): string {
    this.counter += 1;
    return `${this.prefix}-${this.counter.toString(COUNTER_RADIX)}`;
  }
}

const defaultGenerator = new RequestIdGenerator();

/**
 * Produce the next request id from a shared, module-level generator.
 * Prefer a dedicated {@link RequestIdGenerator} instance when a client needs
 * ids independent of other callers in the same process (e.g. tests).
 */
export function nextRequestId(): string {
  return defaultGenerator.next();
}

function randomPrefix(): string {
  const cryptoObj = globalThis.crypto;
  if (cryptoObj && typeof cryptoObj.randomUUID === "function") {
    return cryptoObj.randomUUID().slice(0, 8);
  }
  // Fallback (should be unreachable on Node >= 20, which exposes
  // globalThis.crypto.randomUUID).
  return Math.random().toString(COUNTER_RADIX).slice(2, 10);
}
