"use client";

import { RotateCcw } from "lucide-react";
import { type ReactNode, useCallback, useEffect, useReducer, useState } from "react";
import { cn } from "@/lib/cn";
import {
  TERMINAL_DIALOG_FOOTER,
  TERMINAL_GLYPHS,
  TERMINAL_PERMISSION_TITLE,
  TerminalFrame,
  type TerminalLine,
  type TerminalPermissionChoice,
  type TerminalPermissionLine,
  TerminalRow,
  type TerminalSize,
  terminalToolGlyph,
} from "./TerminalMock";
import { permissionOptions } from "./terminal/labels";
import { VisuallyHidden } from "./VisuallyHidden";

/**
 * A played arcturn session, not a still of one (DESIGN.md §3.1, §3.9).
 *
 * The point the site has to make is that the permission gate is real, and a
 * transcript that already contains its own outcome cannot make it: the reader
 * has no way to tell an enforced stop from a screenshot of one. So this
 * component types the prompt, streams the tool calls, **stops at the gate**,
 * and hands the decision to the reader. Denying is the branch that proves it —
 * the edit never lands, and the turn ends saying so.
 *
 * Every row is drawn by `<TerminalRow>`, from the same structured vocabulary
 * the stills use, so the moving picture and the mocks beside it cannot drift.
 * The one thing drawn here instead is the gate itself: the CLI's bordered
 * permission dialog, with its three answers as real `<button>` rows. That is
 * the whole interaction, and it belongs in the box the product puts it in —
 * not in a strip of key hints bolted under the window.
 *
 * Nothing here is output arcturn would not print. The transcript was checked
 * line for line against `packages/cli/src/display.ts` (`#runStart`'s blank +
 * `▌` prompt, `#toolStart`'s `● glyph name  subject`, `#toolEndBody`'s
 * `⎿ 84 lines` / `⎿ 2 matches · 34 files searched` and the `#diff` head with
 * its `    13 +` continuation rows), `interactive/dialogs.ts`
 * (`permissionDialog`'s line order and `Allow always: <rule> (project)`),
 * and `interactive/app.ts` (the verbatim denial message, and `✓ 12s ·
 * 1.3k tokens` at `runEnd`). Spend is on the status bar because that is where
 * the product keeps it; the checkpoint is *not* a transcript row, because
 * arcturn snapshots silently — that claim lives in the caption instead.
 */

export interface TerminalPlayerProps {
  /** Window title. Defaults to the session the script depicts. */
  title?: string;
  size?: TerminalSize;
  /** §2.3.4 reserves `--shadow-glow` for the primary CTA and the hero terminal. */
  glow?: boolean;
  className?: string;
}

/* ---------------------------------------------------------------- script -- */

const PROMPT = "add input validation to the /signup handler";
const MODEL = "claude-sonnet-4-5";
const CWD = "~/projects/api";
const FILE = "src/routes/signup.ts";

/**
 * Everything above the gate.
 *
 * The last row is the `edit` call itself: `requestPermission` runs *inside*
 * the tool, so the CLI has already printed the call by the time the dialog
 * goes up. That ordering is what makes the gate legible — the row directly
 * above the box names the call the box is asking about.
 */
const SCROLLBACK: readonly TerminalLine[] = [
  { kind: "chrome", model: MODEL, cwd: CWD },
  { kind: "blank" },
  { kind: "user", text: PROMPT },
  { kind: "tool", name: "read", args: FILE },
  { kind: "result", text: "84 lines" },
  { kind: "tool", name: "grep", args: "validate" },
  { kind: "result", text: "2 matches · 34 files searched" },
  { kind: "tool", name: "edit", args: FILE, state: "run" },
];

const SCROLLBACK_ROWS = SCROLLBACK.length;

/** On screen the moment the prompt is sent: header, `#runStart`'s blank, prompt. */
const SUBMITTED_ROWS = 3;

/**
 * The request the dialog is built from.
 *
 * `description` is what `edit` actually passes to `requestPermission`, and
 * `rule` is what `suggestRule` would offer for it — so the three answers are
 * the three answers, not a paraphrase. They are generated by the same
 * `permissionOptions` the stills use.
 */
const GATE: TerminalPermissionLine = {
  kind: "permission",
  tool: "edit",
  subject: FILE,
  description: `Edit ${FILE} (1 replacement)`,
  rule: `edit ${FILE}`,
};

const CHOICES = permissionOptions(GATE);

/** The row the 6s auto-answer takes — and so the row `❯` starts on. */
const AUTO_CHOICE: TerminalPermissionChoice = "once";

type Branch = "allow" | "deny";

/**
 * Both outcomes are five rows, and both fit inside the footprint the dialog
 * already reserves — which is what lets the window keep one height through
 * every phase of both branches.
 *
 * The denial text is verbatim from `interactive/app.ts`: it is the message
 * the model itself receives, carried onto the CLI's own four-space
 * continuation indent by `cont`.
 */
const TAILS: Record<Branch, readonly TerminalLine[]> = {
  allow: [
    { kind: "result", text: `${FILE}  +24 −3`, tone: "good" },
    {
      kind: "result",
      cont: true,
      tone: "good",
      text: "13 +  const parsed = SignupSchema.safeParse(req.body);",
    },
    {
      kind: "result",
      cont: true,
      tone: "good",
      text: "14 +  if (!parsed.success) return res.status(400).json(parsed.error);",
    },
    { kind: "blank" },
    { kind: "done", elapsed: "12s", tokens: "1.3k" },
  ],
  deny: [
    { kind: "result", tone: "bad", text: "The user denied this action. Do not retry it;" },
    { kind: "result", cont: true, tone: "bad", text: "choose another approach or ask." },
    { kind: "blank" },
    { text: "Nothing was written. Want the change as a diff instead?" },
    { kind: "done", elapsed: "9s", tokens: "0.6k" },
  ],
};

const TAIL_ROWS = TAILS.allow.length;

/** Stable per-position keys: the transcript is a fixed grid, not a list. */
const ROW_KEYS = SCROLLBACK.map((_, index) => `row-${index}`);
const TAIL_KEYS = TAILS.allow.map((_, index) => `tail-${index}`);

/** What the status bar's right group reads, per phase. Spend lives there. */
const SPEND: Record<"idle" | "running" | Branch, { cost: string; ctx: string }> = {
  idle: { cost: "$0.00", ctx: "2%" },
  running: { cost: "$0.0087", ctx: "9%" },
  allow: { cost: "$0.0412", ctx: "12%" },
  deny: { cost: "$0.0121", ctx: "9%" },
};

const BASE_DESCRIPTION =
  "An arcturn session. The header names the model and the working directory; a prompt asks for " +
  "input validation on the /signup handler; arcturn reads the route, greps for existing " +
  "validation, then starts an edit to src/routes/signup.ts and stops — a permission dialog asks " +
  "before the write, offering allow once, allow always for that file in this project, or deny.";

const OUTCOMES: Record<Branch, string> = {
  allow:
    " The edit was allowed: it landed as 24 lines added and 3 removed, and the run finished in " +
    "12 seconds having spent four cents.",
  deny:
    " The edit was denied: nothing was written, the model was told the user denied the action " +
    "and not to retry it, and the turn ended there.",
};

/* ----------------------------------------------------------------- timing -- */

/** Cross-fade between the shipped still and the first frame of the run. */
const HANDOFF_MS = 200;
/** No interaction at the gate for this long and the page answers for you. */
const AUTO_MS = 6000;
/** Beat between the gated call appearing and the dialog going up. */
const GATE_MS = 380;

/**
 * One revealed row, and what the activity line reads once it has landed.
 *
 * The `⠋ thinking · 4s · 340 tokens` line has to keep time without a clock of
 * its own: a per-second timer would still be ticking long after the run
 * settled. Each beat carries the numbers instead, so the only timer in the
 * component is the one that schedules the next row.
 */
interface Beat {
  /** Rows on screen after this beat fires. */
  count: number;
  delay: number;
  elapsed: string;
  tokens: string;
}

const TOOL_BEATS: readonly Beat[] = [
  { count: 4, delay: 420, elapsed: "1s", tokens: "120" },
  { count: 5, delay: 300, elapsed: "2s", tokens: "190" },
  { count: 6, delay: 260, elapsed: "3s", tokens: "260" },
  { count: 7, delay: 280, elapsed: "4s", tokens: "340" },
  { count: 8, delay: 260, elapsed: "5s", tokens: "410" },
];

/** What the activity line reads while the gate waits. */
const GATE_CLOCK = { elapsed: "5s", tokens: "410" };

const TAIL_BEATS: Record<Branch, readonly Beat[]> = {
  allow: [
    { count: 1, delay: 300, elapsed: "10s", tokens: "1.0k" },
    { count: 2, delay: 240, elapsed: "11s", tokens: "1.1k" },
    { count: 3, delay: 200, elapsed: "11s", tokens: "1.2k" },
    { count: 4, delay: 200, elapsed: "12s", tokens: "1.3k" },
    { count: 5, delay: 300, elapsed: "12s", tokens: "1.3k" },
  ],
  deny: [
    { count: 1, delay: 300, elapsed: "7s", tokens: "0.4k" },
    { count: 2, delay: 200, elapsed: "7s", tokens: "0.4k" },
    { count: 3, delay: 200, elapsed: "8s", tokens: "0.5k" },
    { count: 4, delay: 260, elapsed: "9s", tokens: "0.6k" },
    { count: 5, delay: 300, elapsed: "9s", tokens: "0.6k" },
  ],
};

/**
 * Gap before the next keystroke. A constant rate reads as a machine typing
 * rather than a person, so the interval is jittered — but derived from the
 * character index, so a replay is identical to the first run.
 */
function keystrokeDelay(index: number): number {
  return 16 + ((index * 37) % 5) * 5;
}

/* ------------------------------------------------------------------ state -- */

type Stage = "static" | "handoff" | "typing" | "tools" | "gate" | "tail" | "done";

interface State {
  stage: Stage;
  /** Characters of {@link PROMPT} in the input box. */
  typed: number;
  /** Leading rows of {@link SCROLLBACK} on screen. */
  visible: number;
  /** Leading rows of the chosen {@link TAILS} entry on screen. */
  tail: number;
  /** The answer given, or `null` while the gate is still open. */
  choice: TerminalPermissionChoice | null;
  /** The answer came from {@link AUTO_MS}, not from the reader. */
  auto: boolean;
  /** Activity-line clock. */
  elapsed: string;
  tokens: string;
}

/** Allow-always is still the allow branch; only the caption knows the difference. */
function branchOf(choice: TerminalPermissionChoice | null): Branch {
  return choice === "deny" ? "deny" : "allow";
}

/**
 * The frame the static export ships: the completed allow branch.
 *
 * Same inversion as `<Reveal>` — the server-rendered markup is the finished,
 * meaningful thing, and JS opts it into the animation afterwards. A player
 * that shipped an empty window would leave a blank rectangle for anyone
 * without JS, for crawlers, and for the gap before hydration.
 */
const SETTLED = {
  stage: "static",
  typed: PROMPT.length,
  visible: SCROLLBACK_ROWS,
  tail: TAIL_ROWS,
  choice: "once",
  auto: false,
  elapsed: "12s",
  tokens: "1.3k",
} as const satisfies State;

type Action =
  | { type: "handoff" }
  | { type: "begin" }
  | { type: "type" }
  | { type: "reveal"; beat: Beat }
  | { type: "gate" }
  | { type: "arm" }
  | { type: "advance"; beat: Beat; last: boolean }
  | { type: "decide"; choice: TerminalPermissionChoice; auto: boolean; instant: boolean }
  | { type: "settle" };

function reduce(state: State, action: Action): State {
  switch (action.type) {
    case "handoff":
      return { ...SETTLED, stage: "handoff" };
    case "begin":
      return {
        stage: "typing",
        typed: 0,
        visible: 1,
        tail: 0,
        choice: null,
        auto: false,
        elapsed: "0s",
        tokens: "0",
      };
    case "type": {
      const typed = Math.min(state.typed + 1, PROMPT.length);
      // Reaching the end of the prompt IS the send, so no extra timer: the
      // prompt leaves the input box and lands as the `▌` row above it.
      if (typed < PROMPT.length) return { ...state, typed };
      return { ...state, typed, stage: "tools", visible: SUBMITTED_ROWS };
    }
    case "reveal":
      return {
        ...state,
        visible: action.beat.count,
        elapsed: action.beat.elapsed,
        tokens: action.beat.tokens,
      };
    case "gate":
      return { ...state, stage: "gate", ...GATE_CLOCK };
    // Reduced motion cannot play the run, but it can still put the reader at
    // the gate: the dialog, no timer, and an answer that lands instantly.
    case "arm":
      return {
        ...SETTLED,
        stage: "gate",
        tail: 0,
        choice: null,
        ...GATE_CLOCK,
      };
    case "advance":
      return {
        ...state,
        tail: action.beat.count,
        elapsed: action.beat.elapsed,
        tokens: action.beat.tokens,
        stage: action.last ? "done" : "tail",
      };
    case "decide": {
      const branch = branchOf(action.choice);
      const last = TAIL_BEATS[branch][TAIL_BEATS[branch].length - 1];
      return {
        ...state,
        stage: action.instant ? "done" : "tail",
        typed: PROMPT.length,
        visible: SCROLLBACK_ROWS,
        tail: action.instant ? TAIL_ROWS : 0,
        choice: action.choice,
        auto: action.auto,
        elapsed: action.instant ? (last?.elapsed ?? state.elapsed) : state.elapsed,
        tokens: action.instant ? (last?.tokens ?? state.tokens) : state.tokens,
      };
    }
    case "settle":
      return { ...SETTLED, stage: "done" };
  }
}

/* --------------------------------------------------------------- component -- */

export function TerminalPlayer({
  title = "arcturn — ~/projects/api",
  size = "lg",
  glow = false,
  className,
}: TerminalPlayerProps) {
  const [state, dispatch] = useReducer(reduce, SETTLED);
  const { stage, typed, visible, tail, choice, auto, elapsed, tokens } = state;
  const branch = branchOf(choice);
  const decided = choice !== null;
  const atGate = stage === "gate";
  /** A run is live: the input box says `↳ steering`, the spinner is up. */
  const live = stage === "tools" || stage === "gate" || stage === "tail";

  // Which dialog row `❯` is on. `null` means nobody is pointing at one, so the
  // marker sits on the row the auto-answer would take.
  const [pointer, setPointer] = useState<TerminalPermissionChoice | null>(null);

  // `null` until the media query has been read, so nothing is scheduled on the
  // strength of a guess about the reader's motion preference.
  const [reduced, setReduced] = useState<boolean | null>(null);

  // The caption only becomes a live region once the reader has touched a
  // control. Autoplay is not a reason to interrupt a screen reader three times
  // on a page nobody asked to hear narrated; a decision they made is.
  const [announce, setAnnounce] = useState(false);

  useEffect(() => {
    const query = window.matchMedia("(prefers-reduced-motion: reduce)");
    const sync = () => setReduced(query.matches);
    sync();
    query.addEventListener("change", sync);
    return () => query.removeEventListener("change", sync);
  }, []);

  useEffect(() => {
    if (reduced === null) return;
    // Reduced motion gets the completed allow branch and no timers at all;
    // replay opens the gate again so the other branch stays one click away.
    dispatch(reduced ? { type: "settle" } : { type: "handoff" });
  }, [reduced]);

  // One scheduler, one timer, one teardown: whatever the stage, at most a
  // single timeout is outstanding, and it is cleared before the next runs —
  // so a finished (or unmounted) player leaves nothing behind.
  useEffect(() => {
    if (reduced !== false) return;
    let timer: ReturnType<typeof setTimeout> | undefined;

    if (stage === "handoff") {
      timer = setTimeout(() => dispatch({ type: "begin" }), HANDOFF_MS);
    } else if (stage === "typing") {
      timer = setTimeout(() => dispatch({ type: "type" }), keystrokeDelay(typed));
    } else if (stage === "tools") {
      const beat = TOOL_BEATS.find((candidate) => candidate.count > visible);
      timer = beat
        ? setTimeout(() => dispatch({ type: "reveal", beat }), beat.delay)
        : setTimeout(() => dispatch({ type: "gate" }), GATE_MS);
    } else if (stage === "gate") {
      // A reader whose pointer (or focus) is on a row is mid-decision, and `❯`
      // has moved to their row: answering for them now would take an answer
      // the marker is no longer offering. The clock restarts when they leave.
      if (pointer === null) {
        timer = setTimeout(
          () => dispatch({ type: "decide", choice: AUTO_CHOICE, auto: true, instant: false }),
          AUTO_MS,
        );
      }
    } else if (stage === "tail") {
      const beats = TAIL_BEATS[branch];
      const beat = beats.find((candidate) => candidate.count > tail);
      if (beat) {
        const last = beat.count === beats.length;
        timer = setTimeout(() => dispatch({ type: "advance", beat, last }), beat.delay);
      }
    }

    return () => clearTimeout(timer);
  }, [reduced, stage, typed, visible, tail, branch, pointer]);

  const decide = useCallback(
    (next: TerminalPermissionChoice) => {
      setAnnounce(true);
      // The dialog goes `visibility: hidden` on the same commit, so no pointer
      // event will fire to clear this; drop it here or `❯` stays parked.
      setPointer(null);
      dispatch({ type: "decide", choice: next, auto: false, instant: reduced === true });
    },
    [reduced],
  );

  const replay = useCallback(() => {
    setAnnounce(true);
    setPointer(null);
    dispatch(reduced ? { type: "arm" } : { type: "begin" });
  }, [reduced]);

  const fade = cn(
    "transition-opacity dur-base ease-out",
    stage === "handoff" ? "opacity-0" : "opacity-100",
  );

  const spend = decided ? SPEND[branch] : live ? SPEND.running : SPEND.idle;

  const input: TerminalLine = {
    kind: "input",
    value: stage === "typing" ? PROMPT.slice(0, typed) : "",
    running: live,
    cursor: stage === "typing",
  };

  const status: TerminalLine = {
    kind: "status",
    model: MODEL,
    mode: "default",
    cost: spend.cost,
    ctx: spend.ctx,
  };

  return (
    <div className={cn("w-full", className)}>
      <TerminalFrame
        title={title}
        size={size}
        glow={glow}
        footer={
          <>
            {/*
              The bottom of the terminal, and the only part of the window that
              is NOT inside `<TerminalFrame>`'s `aria-hidden` subtree — which
              is exactly why the gate lives here. A `<button>` inside that
              subtree would be focusable and hidden at the same time, so the
              dialog's three answers could not be real controls. Everything in
              here that is not a control is `aria-hidden` one level down, so
              screen readers still get the summary and not the ANSI (§2.6).

              `-mt-4` closes the seam that split would otherwise open: the
              scrollback pane above ends on the frame's own `py-4`, and this is
              the same transcript continuing, not a new block.
            */}
            <div className={cn("-mt-4 overflow-x-auto bg-surface-inset px-4 pb-4", fade)}>
              <div className="min-w-max font-mono leading-[1.65]">
                {/*
                  One grid cell, three layers: the dialog, the outcome that
                  replaces it, and the live activity line pinned to the bottom
                  the way the CLI keeps it just above the input box. The dialog
                  is always mounted — hidden, not unmounted — so the tallest
                  thing the window ever shows reserves its height from the
                  first paint, and neither branch nor any phase can resize the
                  frame. `visibility: hidden` also takes its buttons out of the
                  tab order for free.
                */}
                <div className="grid">
                  <div
                    className={cn("col-start-1 row-start-1", atGate ? "term-line" : "invisible")}
                  >
                    <GateDialog
                      marked={pointer ?? AUTO_CHOICE}
                      onPoint={setPointer}
                      onChoose={decide}
                    />
                  </div>
                  <div className="col-start-1 row-start-1" aria-hidden="true">
                    {TAILS[branch].slice(0, tail).map((line, index) => (
                      <TerminalRow key={TAIL_KEYS[index]} line={line} delay={0} />
                    ))}
                  </div>
                  <div className="col-start-1 row-start-1 self-end" aria-hidden="true">
                    {live && !atGate ? (
                      <TerminalRow line={{ kind: "thinking", elapsed, tokens }} delay={0} />
                    ) : null}
                  </div>
                </div>
                <div aria-hidden="true">
                  <TerminalRow line={input} delay={0} />
                  <TerminalRow line={status} delay={0} />
                </div>
              </div>
            </div>
            <div className="flex items-center gap-3 rounded-b-xl border-t border-default bg-surface-card px-3 py-3 sm:px-4">
              <p
                aria-live={announce ? "polite" : "off"}
                className="line-clamp-2 min-h-10 min-w-0 flex-1 text-caption leading-5 text-faint sm:line-clamp-1 sm:min-h-5"
              >
                {caption(stage, choice, auto, reduced === false && pointer === null)}
              </p>
              <button
                type="button"
                onClick={replay}
                aria-label="Replay the session"
                className={cn(
                  "inline-flex size-11 shrink-0 items-center justify-center rounded-md sm:size-9",
                  "border border-default bg-surface-raised text-faint",
                  "transition-colors dur-fast ease-out hover:border-strong hover:text-text",
                )}
              >
                <RotateCcw aria-hidden="true" className="size-4" />
              </button>
            </div>
          </>
        }
      >
        <div className={cn("min-w-max font-mono leading-[1.65]", fade)}>
          {SCROLLBACK.map((line, index) => (
            <PlayerRow key={ROW_KEYS[index]} line={line} shown={index < visible} />
          ))}
        </div>
      </TerminalFrame>
      <VisuallyHidden as="p">
        {`${BASE_DESCRIPTION}${decided ? OUTCOMES[branch] : ""}`}
      </VisuallyHidden>
    </div>
  );
}

/**
 * A scrollback row, or the blank it reserves until it arrives.
 *
 * Swapping the element for `<TerminalRow>` is what starts the fade-up, so a
 * row animates exactly once: when it lands.
 */
function PlayerRow({ line, shown }: { line: TerminalLine; shown: boolean }) {
  if (!shown) return <div className="whitespace-pre"> </div>;
  return <TerminalRow line={line} delay={0} />;
}

/**
 * One character cell — the terminal's grid, as `./terminal/rows` draws it.
 *
 * Half of these marks come from blocks a monospace face may not cover, so a
 * fixed `1ch` box keeps the column honest whatever face ends up drawing them.
 */
function Cell({ children, className }: { children: ReactNode; className?: string }) {
  return <span className={cn("inline-block w-[1ch] text-center", className)}>{children}</span>;
}

interface GateDialogProps {
  /** The row `❯` is on: the pointed-at one, else the auto-answer's. */
  marked: TerminalPermissionChoice;
  onPoint: (choice: TerminalPermissionChoice | null) => void;
  onChoose: (choice: TerminalPermissionChoice) => void;
}

/**
 * The gate: `permissionDialog`, with its answers as buttons.
 *
 * Everything about the box is the product's — `border-warn` because
 * `permissionDialog` builds it with `borderStyle: "warning"`, the title
 * spliced into the top border run, the tool row then the subject then the
 * description then a spacer then the `SelectList` then its `↑↓` hint, in that
 * order. What differs from the still in `./terminal/rows` is that the three
 * rows here are real controls: `❯` marks the one that will be taken, moves to
 * whichever row is hovered or focused, and clicking one answers the gate.
 *
 * Only the buttons are exposed to assistive technology; the painted lines
 * around them are `aria-hidden` (§2.6). Each answer therefore carries the
 * request in its own accessible name — visible label first, so speech input
 * still matches what is on the row — rather than leaning on a wrapper to
 * supply the context.
 */
function GateDialog({ marked, onPoint, onChoose }: GateDialogProps) {
  return (
    <div className="relative my-2 rounded-md border border-warn px-3 py-1.5">
      <span
        aria-hidden="true"
        className="absolute left-2 top-0 -mt-[0.5em] whitespace-pre bg-surface-inset px-1 leading-none text-warn"
      >
        {TERMINAL_PERMISSION_TITLE}
      </span>
      <div aria-hidden="true" className="whitespace-pre text-warn">
        <Cell>{terminalToolGlyph(GATE.tool)}</Cell> {GATE.tool}
      </div>
      <div aria-hidden="true" className="whitespace-pre font-semibold text-text">
        {GATE.subject}
      </div>
      <div aria-hidden="true" className="whitespace-pre text-muted">
        {GATE.description}
      </div>
      <div aria-hidden="true" className="whitespace-pre">
        {" "}
      </div>
      {CHOICES.map((option) => {
        const on = option.key === marked;
        return (
          <button
            key={option.key}
            type="button"
            aria-label={option.key === "always" ? option.label : `${option.label}: edit ${FILE}`}
            onClick={() => onChoose(option.key)}
            onPointerEnter={() => onPoint(option.key)}
            onPointerLeave={() => onPoint(null)}
            onFocus={() => onPoint(option.key)}
            onBlur={() => onPoint(null)}
            className="block w-full whitespace-pre py-px text-left"
          >
            <Cell className="text-accent">{on ? TERMINAL_GLYPHS.pointer : " "}</Cell>{" "}
            <span className={on ? "font-semibold text-accent" : "text-text"}>{option.label}</span>
          </button>
        );
      })}
      <div aria-hidden="true" className="whitespace-pre text-muted">
        {TERMINAL_DIALOG_FOOTER}
      </div>
    </div>
  );
}

/**
 * The line under the window, in the site's voice rather than the terminal's.
 *
 * It carries the two facts the transcript cannot: that six seconds of silence
 * answers the gate, and that the edit was snapshotted before it landed —
 * arcturn checkpoints silently, so printing a checkpoint row would be output
 * the product never writes (§3.9).
 */
function caption(
  stage: Stage,
  choice: TerminalPermissionChoice | null,
  auto: boolean,
  counting: boolean,
): string {
  if (stage === "gate") {
    return counting
      ? "Waiting for you. Six seconds with no answer takes Allow once."
      : "Waiting for you: allow once, allow always, or deny.";
  }
  if (choice === null) return "Running the session — it stops before it writes.";
  if (choice === "deny") return "Denied. Nothing was written, and the model was told why.";
  if (choice === "always") return "Allowed, and the rule saved to this project. The edit landed.";
  if (auto) return "Allowed automatically after six seconds. Replay to answer it.";
  return "Allowed. The edit landed, snapshotted first so /rewind can undo it.";
}
