/**
 * File-state checkpoints ("rewind"): before any file-mutating tool runs, the
 * target file's current content (or absence) is snapshotted, so a user can
 * later restore the workspace to how it looked at any earlier turn.
 *
 * Storage lives in a caller-provided directory (the integration is expected
 * to pass something like `~/.arcturn/checkpoints/<sessionId>`):
 *
 * ```text
 * <dir>/manifest.jsonl   append-only log of turn/file/error records
 * <dir>/blobs/<sha256>   content-addressed file snapshots
 * ```
 *
 * The manifest is a flat, append-only JSONL log. Each line is one of:
 *
 * - `{ kind: "turn", id, label, timestamp }` — a user-prompt boundary.
 * - `{ kind: "file", turnId, path, blob, mode?, timestamp }` — the state of
 *   `path` immediately before it was first touched during `turnId`. `blob` is
 *   a sha256 hex digest naming a file under `blobs/`, or `null` when the file
 *   did not exist yet. `mode` carries the permission bits so a restore puts
 *   an executable back executable; it is absent on manifests written before
 *   the field existed, and on records whose file did not exist.
 * - `{ kind: "error", turnId, path, message, timestamp }` — a snapshot that
 *   failed to capture `path` (e.g. a permission error reading it). Recorded
 *   so the failure is visible without ever blocking the tool call that
 *   triggered it.
 *
 * See `INTEGRATION-checkpoints.md` at the repo root for how a host
 * application is expected to wire this into `runtime.ts` and a `/rewind`
 * command.
 */

import { createHash, randomUUID } from "node:crypto";
import { chmod, mkdir, readFile, rename, stat, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve, sep } from "node:path";
import { resolvePath, resolveSubjectPath } from "@arcturn/tools";
import type { Tool, ToolExecutionContext } from "@arcturn/types";

/** A user-prompt boundary; every snapshot taken afterwards belongs to it. */
export interface CheckpointTurnRecord {
  kind: "turn";
  /** Unique id, generated by {@link CheckpointStore.beginTurn}. */
  id: string;
  /** Caller-supplied label, conventionally the first ~60 chars of the prompt. */
  label: string;
  timestamp: number;
}

/** The state of one file immediately before its first mutation in a turn. */
export interface CheckpointFileRecord {
  kind: "file";
  /** Turn during which this snapshot was taken. */
  turnId: string;
  /** Absolute path snapshotted. */
  path: string;
  /** sha256 hex digest of the file's content under `blobs/`, or `null` if the file did not exist. */
  blob: string | null;
  /**
   * The file's permission bits at snapshot time, or absent when the file did
   * not exist (and on manifests written before this field existed).
   *
   * Content alone is not the pre-image. A restore writes through a temp file
   * and a rename, which gives the result the process umask's mode — so
   * rewinding past an edit to a shell script, a git hook or any other
   * executable left the bytes right and the file un-runnable, with nothing
   * in the restore's report to say so.
   */
  mode?: number;
  timestamp: number;
}

/** A snapshot attempt that failed; recorded instead of blocking the tool call. */
export interface CheckpointErrorRecord {
  kind: "error";
  /** Turn during which the failed snapshot was attempted. */
  turnId: string;
  /** Path the snapshot was attempting to capture. */
  path: string;
  /** Human-readable failure reason. */
  message: string;
  timestamp: number;
}

/** One line of the checkpoint manifest. */
export type CheckpointManifestEntry =
  | CheckpointTurnRecord
  | CheckpointFileRecord
  | CheckpointErrorRecord;

/** Summary row returned by {@link CheckpointStore.listTurns}. */
export interface CheckpointTurnSummary {
  id: string;
  label: string;
  timestamp: number;
  /** Number of distinct files snapshotted during this turn. */
  fileCount: number;
}

/** One failure to apply a restore, alongside the path it was attempting. */
export interface CheckpointRestoreError {
  path: string;
  message: string;
}

/** What a restore would do to one path. See {@link CheckpointRestorePlan}. */
export interface CheckpointRestoreStep {
  /** Absolute path, exactly as the manifest recorded it. */
  path: string;
  /**
   * `"restore"` — the pre-image is written back over the file.
   * `"delete"` — the file did not exist at that point and is removed.
   * `"refuse"` — the path fails {@link CreateCheckpointStoreOptions.restoreRoot}
   *   and is left alone; `reason` says why.
   */
  action: "restore" | "delete" | "refuse";
  /** Why a `"refuse"` step is refused. Absent otherwise. */
  reason?: string;
}

/**
 * Everything a restore to one turn would do, without doing any of it.
 *
 * Exists so a *picker* can be honest. A menu offering "rewind to here" without
 * saying what it costs is a menu somebody clicks by accident, and the cost is
 * not something a caller can compute for itself — it is the union of the
 * earliest snapshot per path from that turn to the end of the manifest, and
 * the confinement decision on each one.
 *
 * Deliberately the *same* computation {@link CheckpointStore.restore} applies:
 * `restore` is this plan plus the writes, so there is exactly one place that
 * decides which paths are in range and which are refused. A second preview
 * that walked the manifest with its own rules would eventually show a file
 * count that a restore then disagreed with, and the disagreement would only
 * be visible on somebody's disk.
 */
export interface CheckpointRestorePlan {
  /** The turn this plan restores to. */
  turnId: string;
  /** One step per distinct path, in manifest order. */
  steps: CheckpointRestoreStep[];
}

/** Outcome of {@link CheckpointStore.restore}. */
export interface CheckpointRestoreResult {
  /** Paths whose content was written back from a blob. */
  restored: string[];
  /** Paths that were removed because their earliest record was "absent". */
  deleted: string[];
  /** Paths that could not be restored (e.g. a missing blob), with a reason. */
  errors: CheckpointRestoreError[];
}

/** File-state checkpoint store backing `/rewind`. */
export interface CheckpointStore {
  /**
   * Record a new user-prompt boundary. Every {@link CheckpointStore.snapshot}
   * call made afterwards (until the next `beginTurn`) belongs to this turn.
   *
   * @param label - Short human-readable label, conventionally the first ~60
   *   characters of the user's prompt.
   * @returns The new turn's id.
   */
  beginTurn(label: string): Promise<string>;

  /**
   * Record the current content (or absence) of `path`, if it has not
   * already been recorded during the active turn.
   *
   * Later calls for the same `path` in the same turn are no-ops, so the
   * very first snapshot — the state from just before the turn's first
   * mutation — is always what gets preserved.
   *
   * Never rejects: a failure to read `path` is written to the manifest as
   * a {@link CheckpointErrorRecord} instead of being thrown, so a checkpoint
   * failure never blocks the tool call that triggered it.
   *
   * @param path - Absolute path to snapshot.
   * @throws Only when called before any {@link CheckpointStore.beginTurn}.
   */
  snapshot(path: string): Promise<void>;

  /** Every recorded turn, oldest first. */
  listTurns(): Promise<CheckpointTurnSummary[]>;

  /**
   * What {@link CheckpointStore.restore} would do for `turnId`, without
   * touching a single file.
   *
   * @param turnId - Turn a caller is considering rewinding to.
   * @returns The steps, including the ones that would be refused.
   * @throws When `turnId` does not name a recorded turn.
   */
  planRestore(turnId: string): Promise<CheckpointRestorePlan>;

  /**
   * Restore the workspace to how it looked immediately before `turnId`.
   *
   * For `turnId` and every turn recorded after it, each touched path's
   * *earliest* snapshot in that range is applied: files get their
   * pre-change content written back, and files whose earliest record is
   * "absent" (never existed before the range) are deleted.
   *
   * Applies exactly {@link CheckpointStore.planRestore}'s steps and nothing
   * else, so what a caller was shown and what a caller gets are one
   * computation.
   *
   * @param turnId - Turn to rewind to.
   * @returns Paths restored, paths deleted, and any failures encountered.
   * @throws When `turnId` does not name a recorded turn.
   */
  restore(turnId: string): Promise<CheckpointRestoreResult>;
}

const MANIFEST_FILE = "manifest.jsonl";
const BLOBS_DIR = "blobs";

/**
 * The one sentence a confinement refusal gets, quoted by both the plan and the
 * restore so a preview and its outcome cannot word the same refusal
 * differently.
 */
const OUTSIDE_RESTORE_ROOT = "outside the workspace restore root; skipped";

function isMissing(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    (error as NodeJS.ErrnoException).code === "ENOENT"
  );
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

/** Parse a line, or return undefined when it is not valid JSON. */
function tryParseLine(line: string): CheckpointManifestEntry | undefined {
  try {
    return JSON.parse(line) as CheckpointManifestEntry;
  } catch {
    return undefined;
  }
}

/**
 * Write `data` to `path` via a temp file + rename, so a crash cannot leave a
 * partial file.
 *
 * `mode` is applied to the temp file *before* the rename, so the file is never
 * momentarily visible at the destination with the wrong bits. Absent (an old
 * manifest, or a pre-image that did not exist) leaves the umask default, which
 * is exactly what this did before the mode was recorded.
 */
async function writeFileAtomic(path: string, data: Buffer, mode?: number): Promise<void> {
  const parent = dirname(path);
  await mkdir(parent, { recursive: true });
  const tmp = join(parent, `.checkpoint-tmp-${randomUUID()}`);
  await writeFile(tmp, data);
  if (mode !== undefined) await chmod(tmp, mode);
  await rename(tmp, path);
}

/**
 * File-backed {@link CheckpointStore}.
 *
 * All manifest appends and blob writes are serialized through a single
 * promise queue (the same pattern `JsonlSessionStore` uses for session
 * files), so concurrent `snapshot()` calls can never interleave into a
 * corrupt manifest line or race on the "already recorded this turn" check.
 */
class FileCheckpointStore implements CheckpointStore {
  readonly #dir: string;
  /** Serializes every manifest append and blob write. */
  #queue: Promise<unknown> = Promise.resolve();
  /** `${turnId}\0${path}` keys already snapshotted, so repeats become no-ops. */
  readonly #recorded = new Set<string>();
  #currentTurnId: string | undefined;
  #dirReady: Promise<void> | undefined;

  readonly #restoreRoot: string | undefined;

  constructor(dir: string, restoreRoot?: string) {
    this.#restoreRoot = restoreRoot === undefined ? undefined : resolve(restoreRoot);
    this.#dir = dir;
  }

  async beginTurn(label: string): Promise<string> {
    const id = randomUUID();
    const timestamp = Date.now();
    await this.#enqueue(async () => {
      this.#currentTurnId = id;
      await this.#append({ kind: "turn", id, label, timestamp });
    });
    return id;
  }

  async snapshot(path: string): Promise<void> {
    // A snapshot with no open turn would be unrecoverable if dropped — e.g. a
    // sub-agent driven outside a parent run. Open an untracked turn instead
    // so the pre-image is still reachable from /rewind.
    const turnId = this.#currentTurnId ?? (await this.beginTurn("(untracked)"));
    const key = `${turnId}\0${path}`;
    await this.#enqueue(async () => {
      if (this.#recorded.has(key)) return;
      this.#recorded.add(key);
      const timestamp = Date.now();
      try {
        const captured = await this.#captureBlob(path);
        await this.#append({
          kind: "file",
          turnId,
          path,
          blob: captured.blob,
          ...(captured.mode === undefined ? {} : { mode: captured.mode }),
          timestamp,
        });
      } catch (error) {
        await this.#append({
          kind: "error",
          turnId,
          path,
          message: errorMessage(error),
          timestamp,
        });
      }
    });
  }

  async listTurns(): Promise<CheckpointTurnSummary[]> {
    const entries = await this.#readManifest();
    const summaries: CheckpointTurnSummary[] = [];
    let current: CheckpointTurnSummary | undefined;
    for (const entry of entries) {
      if (entry.kind === "turn") {
        current = { id: entry.id, label: entry.label, timestamp: entry.timestamp, fileCount: 0 };
        summaries.push(current);
      } else if (entry.kind === "file" && current) {
        current.fileCount += 1;
      }
    }
    return summaries;
  }

  async planRestore(turnId: string): Promise<CheckpointRestorePlan> {
    const entries = await this.#readManifest();
    const startIndex = entries.findIndex((entry) => entry.kind === "turn" && entry.id === turnId);
    if (startIndex === -1) {
      throw new Error(`checkpoints: unknown turn id ${JSON.stringify(turnId)}`);
    }

    const earliestByPath = new Map<string, CheckpointFileRecord>();
    for (let i = startIndex; i < entries.length; i++) {
      const entry = entries[i]!;
      if (entry.kind !== "file") continue;
      if (!earliestByPath.has(entry.path)) earliestByPath.set(entry.path, entry);
    }

    const steps: CheckpointRestoreStep[] = [];
    for (const record of earliestByPath.values()) {
      if (!this.#insideRestoreRoot(record.path)) {
        steps.push({
          path: record.path,
          action: "refuse",
          reason: OUTSIDE_RESTORE_ROOT,
        });
        continue;
      }
      steps.push({ path: record.path, action: record.blob === null ? "delete" : "restore" });
    }
    return { turnId, steps };
  }

  async restore(turnId: string): Promise<CheckpointRestoreResult> {
    const entries = await this.#readManifest();
    const startIndex = entries.findIndex((entry) => entry.kind === "turn" && entry.id === turnId);
    if (startIndex === -1) {
      throw new Error(`checkpoints: unknown turn id ${JSON.stringify(turnId)}`);
    }

    const earliestByPath = new Map<string, CheckpointFileRecord>();
    for (let i = startIndex; i < entries.length; i++) {
      const entry = entries[i]!;
      if (entry.kind !== "file") continue;
      if (!earliestByPath.has(entry.path)) earliestByPath.set(entry.path, entry);
    }

    const restored: string[] = [];
    const deleted: string[] = [];
    const errors: CheckpointRestoreError[] = [];

    for (const record of earliestByPath.values()) {
      // The same gate `planRestore` reports, read from the same function: a
      // preview that computed confinement separately from the writer is how a
      // picker comes to promise a restore the store then refuses.
      if (!this.#insideRestoreRoot(record.path)) {
        errors.push({ path: record.path, message: OUTSIDE_RESTORE_ROOT });
        continue;
      }
      if (record.blob === null) {
        try {
          await unlink(record.path);
          deleted.push(record.path);
        } catch (error) {
          if (!isMissing(error)) errors.push({ path: record.path, message: errorMessage(error) });
        }
        continue;
      }

      try {
        const content = await readFile(this.#blobPath(record.blob));
        await writeFileAtomic(record.path, content, record.mode);
        restored.push(record.path);
      } catch (error) {
        errors.push({ path: record.path, message: errorMessage(error) });
      }
    }

    return { restored, deleted, errors };
  }

  /**
   * Whether a manifest-recorded path may be written by a restore.
   *
   * The one gate, read by both {@link FileCheckpointStore.planRestore} and
   * {@link FileCheckpointStore.restore}. A manifest is an append-only file on
   * disk that a tool with a wide `cwd` — or a tamperer — can have put an
   * out-of-tree path into, and this is the only thing standing between such a
   * record and a write outside the workspace.
   */
  #insideRestoreRoot(path: string): boolean {
    if (this.#restoreRoot === undefined) return true;
    const resolved = resolve(path);
    return resolved === this.#restoreRoot || resolved.startsWith(this.#restoreRoot + sep);
  }

  /**
   * Read the file at `path` (or note its absence) and store it
   * content-addressed, alongside the permission bits a restore has to put
   * back with it.
   *
   * The mode is read from the same file the content came from, and only when
   * the content was readable — a path that did not exist has no mode to
   * restore, and `blob: null` already says a restore should delete it.
   */
  async #captureBlob(path: string): Promise<{ blob: string | null; mode?: number }> {
    let content: Buffer;
    let mode: number | undefined;
    try {
      content = await readFile(path);
      // A failure to stat is not a failure to snapshot: the bytes are the
      // pre-image, the mode is a refinement on it.
      mode = await stat(path)
        .then((info) => info.mode & 0o7777)
        .catch(() => undefined);
    } catch (error) {
      if (isMissing(error)) return { blob: null };
      throw error;
    }
    const sha = createHash("sha256").update(content).digest("hex");
    const withMode = (blob: string) => (mode === undefined ? { blob } : { blob, mode });
    const blobPath = this.#blobPath(sha);
    try {
      await stat(blobPath);
      return withMode(sha); // Already stored under this content hash.
    } catch {
      // Fall through to write it below.
    }
    await mkdir(this.#blobsDir(), { recursive: true });
    const tmp = join(this.#blobsDir(), `.tmp-${randomUUID()}`);
    await writeFile(tmp, content);
    await rename(tmp, blobPath);
    return withMode(sha);
  }

  async #append(entry: CheckpointManifestEntry): Promise<void> {
    await this.#ensureDir();
    await writeFile(this.#manifestPath(), `${JSON.stringify(entry)}\n`, { flag: "a" });
  }

  async #readManifest(): Promise<CheckpointManifestEntry[]> {
    let raw: string;
    try {
      raw = await readFile(this.#manifestPath(), "utf8");
    } catch (error) {
      if (isMissing(error)) return [];
      throw error;
    }
    const entries: CheckpointManifestEntry[] = [];
    for (const line of raw.split("\n")) {
      if (line.trim().length === 0) continue;
      const parsed = tryParseLine(line);
      if (parsed !== undefined) entries.push(parsed);
    }
    return entries;
  }

  #manifestPath(): string {
    return join(this.#dir, MANIFEST_FILE);
  }

  #blobsDir(): string {
    return join(this.#dir, BLOBS_DIR);
  }

  #blobPath(sha: string): string {
    return join(this.#blobsDir(), sha);
  }

  async #ensureDir(): Promise<void> {
    this.#dirReady ??= mkdir(this.#dir, { recursive: true }).then(() => undefined);
    await this.#dirReady;
  }

  /** Chain `fn` onto the write queue so it never overlaps another queued op. */
  #enqueue<T>(fn: () => Promise<T>): Promise<T> {
    const result = this.#queue.catch(() => undefined).then(fn);
    this.#queue = result.catch(() => undefined);
    return result;
  }
}

/**
 * Create a {@link CheckpointStore} backed by `dir`.
 *
 * The directory (and its `blobs/` subdirectory) is created lazily on first
 * write; `dir` should be unique per session, e.g. `~/.arcturn/checkpoints/<sessionId>`.
 *
 * @param dir - Directory to store the manifest and blobs in.
 */
export function createCheckpointStore(
  dir: string,
  options: CreateCheckpointStoreOptions = {},
): CheckpointStore {
  return new FileCheckpointStore(dir, options.restoreRoot);
}

/** Options for {@link createCheckpointStore}. */
export interface CreateCheckpointStoreOptions {
  /**
   * Confines {@link CheckpointStore.restore} to paths under this directory.
   * A manifest record outside it — e.g. from a tampered manifest file — is
   * reported as an error instead of written. Snapshots are not confined:
   * capturing pre-images is harmless, and a tool may legitimately be allowed
   * to write outside the workspace; only the store-initiated *mutation* on
   * restore is gated.
   */
  readonly restoreRoot?: string;
}

const CHECKPOINTED_TOOL_NAMES = new Set(["write", "edit"]);

/**
 * Wrap the `write` and `edit` tools so every call snapshots its target file
 * (via `store.snapshot`) before the underlying tool executes. Every other
 * tool is returned unchanged.
 *
 * The path is resolved with the same `resolvePath(ctx.cwd, input.path)` the
 * built-in `write`/`edit` tools use internally (see
 * `packages/tools/src/write.ts`, `packages/tools/src/edit.ts` and the
 * `ToolExecutionContext` shape in `packages/types/src/tools.ts`), so the
 * snapshot key always matches the file the tool is about to touch.
 *
 * A `snapshot()` failure — including a store bug such as calling before
 * `beginTurn()` — never blocks the tool call: it is caught here and, for
 * ordinary capture failures, also recorded by `snapshot()` itself as a
 * `CheckpointErrorRecord` in the manifest. Callers that want visibility into
 * checkpoint failures should read `listTurns()`/the manifest rather than
 * this wrapper's return value.
 *
 * @param tools - Tools to (selectively) wrap.
 * @param store - Checkpoint store to snapshot into.
 */
export function wrapToolsWithCheckpoints(tools: readonly Tool[], store: CheckpointStore): Tool[] {
  return tools.map((tool) => {
    if (!CHECKPOINTED_TOOL_NAMES.has(tool.definition.name)) return tool;
    // Spread first so extra tool surface (e.g. bindAgent) survives the wrap.
    return {
      ...tool,
      execute: async (input: Record<string, unknown>, ctx: ToolExecutionContext) => {
        const rawPath = input.path;
        if (typeof rawPath === "string" && rawPath.length > 0) {
          const absolutePath = resolvePath(ctx.cwd, rawPath);
          try {
            // The DESTINATION, not the spelling — the same subject the
            // permission prompt named. `resolvePath` alone normalizes `..`
            // but not symlinks, so a snapshot of a symlinked file recorded
            // the LINK's path while the tool wrote through it to the target:
            // the restore then renamed a pre-image over the link, destroying
            // it and leaving the real file holding the change the rewind was
            // supposed to undo. `resolveSubjectPath` returns `absolutePath`
            // unchanged for any path with no link in it, so nothing else
            // moves.
            // A resolution failure must not cost the snapshot: fall back to
            // the lexical path, which is what this used before subjects were
            // resolved at all. Losing the pre-image is the expensive failure,
            // and it is silent — nothing downstream reports a turn that has
            // no record for a file it touched.
            const subject = await resolveSubjectPath(ctx.cwd, absolutePath).catch(
              () => absolutePath,
            );
            await store.snapshot(subject);
          } catch {
            // See TSDoc above: never block the tool call on a checkpoint failure.
          }
        }
        return tool.execute(input, ctx);
      },
    };
  });
}
