/**
 * Shell completion script generation for the `arcturn` CLI.
 *
 * `arcturn completions <bash|zsh|fish>` prints a self-contained script for the
 * requested shell. Everything the scripts know about — flags, their value
 * hints, enum choices, and subcommands — comes from a single declarative
 * table, {@link DEFAULT_COMPLETION_SPEC}. When a flag is added to `args.ts`,
 * updating that table (and nothing else) keeps completions in sync.
 *
 * The scripts are plain text generated by string templates; no shell is
 * invoked at generation time. `--model` is the one place a script calls back
 * into `arcturn` at completion time (`arcturn --list-models`), since the model
 * catalog can grow via extensions and would otherwise drift from a static
 * list. That call is guarded in every shell so a slow or failing `arcturn`
 * degrades to "no suggestions" rather than hanging or erroring the shell.
 */

/** A shell `arcturn completions` knows how to target. */
export type CompletionShell = "bash" | "zsh" | "fish";

/** Every supported shell, in the order they are documented. */
export const COMPLETION_SHELLS: readonly CompletionShell[] = ["bash", "zsh", "fish"];

/** Narrow an arbitrary string to a {@link CompletionShell}. */
export function isCompletionShell(value: string): value is CompletionShell {
  return (COMPLETION_SHELLS as readonly string[]).includes(value);
}

/**
 * Thrown by {@link generateCompletions} when asked for a shell it does not
 * recognise.
 *
 * Kept as a distinct class (rather than a plain `Error`) so callers such as
 * `main.ts` can match on `instanceof` and turn it into the same tidy
 * usage-error exit path used for a bad `--permission-mode` or `--output-format`.
 */
export class UnknownCompletionShellError extends Error {
  /** The value that was rejected. */
  readonly shell: string;

  constructor(shell: string) {
    super(`Unknown completion shell "${shell}". Expected one of: ${COMPLETION_SHELLS.join(", ")}.`);
    this.name = "UnknownCompletionShellError";
    this.shell = shell;
  }
}

/** What kind of value a flag's argument holds, so a script knows how to complete it. */
export type CompletionValueHint = "model" | "path" | "mode" | "format" | "session" | "number";

/** One flag `arcturn` accepts, as far as completion needs to know. */
export interface CompletionFlag {
  /** Long form, e.g. `"--model"`. */
  readonly long: string;
  /** Short alias, e.g. `"-m"`, when one exists. */
  readonly short?: string;
  /** Whether the flag takes a value (`--model x`) or is a bare switch. */
  readonly takesValue: boolean;
  /** What the value represents, when {@link takesValue} is true. */
  readonly valueHint?: CompletionValueHint;
  /** Fixed set of legal values, when the value is an enum (e.g. permission modes). */
  readonly enumValues?: readonly string[];
  /** One-line description shown by shells that support it (zsh, fish). */
  readonly description: string;
}

/** A positional sub-command, optionally with its own fixed set of child words. */
export interface CompletionSubcommand {
  /** The word itself, e.g. `"completions"`. */
  readonly name: string;
  /** One-line description shown by shells that support it. */
  readonly description: string;
  /** Fixed words that can follow this subcommand (e.g. `completions`' shells). */
  readonly children?: readonly CompletionSubcommand[];
}

/** Everything a completion script needs: the program name, its flags, and its subcommands. */
export interface CompletionSpec {
  /** Executable name completions are registered for (`arcturn`). */
  readonly program: string;
  /** Every flag, in help-text order. */
  readonly flags: readonly CompletionFlag[];
  /** Every top-level positional command. */
  readonly subcommands: readonly CompletionSubcommand[];
}

/**
 * The flag and subcommand table mirrored from `args.ts` and `main.ts`.
 *
 * This is the single source of truth for what the generated scripts offer.
 * Kept as a plain data table (not derived by inspecting `args.ts` at
 * runtime) so this file never needs to import parser internals — a change to
 * the real flag list is a one-line diff here, and `completions.test.ts`
 * exists specifically to make forgetting that diff loud.
 */
export const DEFAULT_COMPLETION_SPEC: CompletionSpec = {
  program: "arcturn",
  flags: [
    {
      long: "--print",
      short: "-p",
      takesValue: false,
      description: "Run once, print the final assistant message, and exit.",
    },
    {
      long: "--output-format",
      takesValue: true,
      valueHint: "format",
      enumValues: ["text", "json"],
      description: 'With --print: "text" (default) or "json" (NDJSON of every agent event).',
    },
    {
      long: "--model",
      short: "-m",
      takesValue: true,
      valueHint: "model",
      description: "Model to use (see --list-models).",
    },
    {
      long: "--continue",
      short: "-c",
      takesValue: false,
      description: "Resume the most recent session in this directory.",
    },
    {
      long: "--resume",
      short: "-r",
      takesValue: true,
      valueHint: "session",
      description: "Resume a specific session.",
    },
    {
      long: "--permission-mode",
      takesValue: true,
      valueHint: "mode",
      enumValues: ["default", "acceptEdits", "plan", "yolo"],
      description: "Starting permission mode.",
    },
    {
      long: "--cwd",
      takesValue: true,
      valueHint: "path",
      description: "Working directory for tools, config and sessions.",
    },
    {
      long: "--mcp",
      takesValue: false,
      description: "Start configured MCP servers (default).",
    },
    {
      long: "--no-mcp",
      takesValue: false,
      description: "Do not start any configured MCP servers.",
    },
    {
      long: "--max-turns",
      takesValue: true,
      valueHint: "number",
      description: "Stop a run after n model turns.",
    },
    {
      long: "--max-cost",
      takesValue: true,
      valueHint: "number",
      description: "Abort the run once it has cost this much (USD).",
    },
    {
      long: "--dry-run",
      takesValue: false,
      description: "Send file edits to a shadow copy; review with /diff.",
    },
    {
      long: "--no-dry-run",
      takesValue: false,
      description: "Apply file edits for real (the default).",
    },
    {
      long: "--trace",
      takesValue: false,
      description: "Write one JSON line per finished telemetry span to stderr.",
    },
    {
      long: "--no-trace",
      takesValue: false,
      description: "Do not write telemetry spans (the default).",
    },
    {
      long: "--host",
      takesValue: true,
      description: "With serve: interface to bind (default 127.0.0.1).",
    },
    {
      long: "--port",
      takesValue: true,
      valueHint: "number",
      description: "With serve: port to bind (default 7717).",
    },
    {
      long: "--token",
      takesValue: true,
      description: "With serve/attach: shared auth token (generated if omitted).",
    },
    {
      long: "--web",
      takesValue: false,
      description: "With serve: also serve the browser client.",
    },
    {
      long: "--web-port",
      takesValue: true,
      valueHint: "number",
      description: "With serve --web: port for the browser client.",
    },
    {
      long: "--web-origin",
      takesValue: true,
      description: "With serve --web: an extra allowed browser origin (repeatable).",
    },
    {
      long: "--cassette",
      takesValue: true,
      valueHint: "path",
      description: "With bisect: the VCR recording to compare against.",
    },
    {
      long: "--record",
      takesValue: true,
      valueHint: "path",
      description: "Record this run's model and tool calls to a cassette file.",
    },
    {
      long: "--help",
      short: "-h",
      takesValue: false,
      description: "Show help.",
    },
    {
      long: "--version",
      short: "-v",
      takesValue: false,
      description: "Print the version.",
    },
    {
      long: "--list-models",
      takesValue: false,
      description: "Print the model catalog and exit.",
    },
    {
      long: "--list-providers",
      takesValue: false,
      description: "Print every provider and preset endpoint, and exit.",
    },
  ],
  subcommands: [
    {
      name: "completions",
      description: "Print a shell completion script.",
      children: COMPLETION_SHELLS.map((shell) => ({
        name: shell,
        description: `${shell} completion script.`,
      })),
    },
    {
      name: "replay",
      description: "Re-run a session's prompts, optionally on another model.",
    },
    { name: "audit", description: "Print the audit trail for a session." },
    { name: "blame", description: "Explain which turn and evidence wrote each line." },
    { name: "bisect", description: "Find the turn where behaviour left a recording." },
    { name: "serve", description: "Host sessions over WebSocket for remote attach." },
    { name: "acp", description: "Speak the Agent Client Protocol on stdio (for editors)." },
    { name: "attach", description: "Drive a session hosted by another arcturn serve." },
    {
      name: "doctor",
      description: "Probe every configured provider endpoint and print a verdict.",
    },
    {
      name: "mcp",
      description: "Manage MCP servers.",
      children: [
        { name: "list", description: "Show configured servers and where they're defined." },
        { name: "get", description: "Print one server's configuration." },
        { name: "add", description: "Add a stdio or HTTP MCP server." },
        { name: "remove", description: "Remove a server." },
        { name: "auth", description: "Authorize an OAuth HTTP server in the browser." },
        { name: "logout", description: "Delete the stored OAuth credentials for a server." },
      ],
    },
    { name: "add", description: "Install a package from a git URL, shorthand or local path." },
    { name: "inspect", description: "Print what installing a source WOULD add. Installs nothing." },
    { name: "packages", description: "List installed packages and what each one provides." },
    { name: "update", description: "Re-fetch one package, or every unpinned one." },
    { name: "remove", description: "Uninstall a package and unlink everything it added." },
    {
      name: "new",
      description: "Scaffold a skill, agent or workflow file.",
      children: [
        { name: "skill", description: "A markdown skill." },
        { name: "agent", description: "An agent role." },
        { name: "workflow", description: "A workflow." },
      ],
    },
  ],
};

/**
 * Generate a completion script for one shell.
 *
 * @param shell - `"bash"`, `"zsh"` or `"fish"`. Any other value throws
 *   {@link UnknownCompletionShellError} rather than returning an empty or
 *   partial script, so a typo surfaces immediately.
 * @param spec - Flag/subcommand table to render; defaults to
 *   {@link DEFAULT_COMPLETION_SPEC}.
 * @returns The full script, ready to write to a file or `eval`.
 */
export function generateCompletions(
  shell: string,
  spec: CompletionSpec = DEFAULT_COMPLETION_SPEC,
): string {
  if (!isCompletionShell(shell)) {
    throw new UnknownCompletionShellError(shell);
  }
  switch (shell) {
    case "bash":
      return generateBashCompletions(spec);
    case "zsh":
      return generateZshCompletions(spec);
    case "fish":
      return generateFishCompletions(spec);
  }
}

/** Escape a string for embedding inside a zsh single-quoted literal. */
function escapeZshSingleQuoted(value: string): string {
  return value.replace(/'/g, "'\\''");
}

/** Escape a string for embedding inside a fish single-quoted literal. */
function escapeFishSingleQuoted(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/'/g, "\\'");
}

/** Long and short forms of a flag, flattened into one list. */
function flagWords(flag: CompletionFlag): string[] {
  return flag.short ? [flag.long, flag.short] : [flag.long];
}

/**
 * The POSIX shell body shared by the bash and zsh scripts for resolving
 * `--model` candidates.
 *
 * Wrapped in `timeout` when available so a hung or slow `arcturn` (e.g. waiting
 * on a network-backed extension) cannot stall tab completion; when `timeout`
 * is not on `$PATH`, the call still runs but errors and empty output are
 * swallowed, so the worst case is no suggestions rather than a shell error.
 */
function posixListModelsFunction(program: string, functionName: string): string {
  return [
    `${functionName}() {`,
    `  if command -v timeout >/dev/null 2>&1; then`,
    `    timeout 0.3 ${program} --list-models 2>/dev/null | awk 'NR>1{print $1}'`,
    `  else`,
    `    ${program} --list-models 2>/dev/null | awk 'NR>1{print $1}'`,
    `  fi`,
    `}`,
  ].join("\n");
}

/** Render the bash completion script. */
function generateBashCompletions(spec: CompletionSpec): string {
  const program = spec.program;
  const funcName = `_${program}_completions`;
  const listModelsFn = `_${program}_list_models`;

  const allFlagWords = spec.flags.flatMap(flagWords).join(" ");
  const topLevelWords = spec.subcommands.map((s) => s.name).join(" ");

  const cases: string[] = [];

  for (const flag of spec.flags) {
    if (!flag.takesValue) continue;
    const pattern = flagWords(flag).join("|");
    if (flag.enumValues && flag.enumValues.length > 0) {
      cases.push(
        [
          `    ${pattern})`,
          `      COMPREPLY=( $(compgen -W "${flag.enumValues.join(" ")}" -- "$cur") )`,
          `      return 0`,
          `      ;;`,
        ].join("\n"),
      );
    } else if (flag.valueHint === "model") {
      cases.push(
        [
          `    ${pattern})`,
          `      local models`,
          `      models="$(${listModelsFn})"`,
          `      if [ -n "$models" ]; then`,
          `        COMPREPLY=( $(compgen -W "$models" -- "$cur") )`,
          `      fi`,
          `      return 0`,
          `      ;;`,
        ].join("\n"),
      );
    } else if (flag.valueHint === "path") {
      cases.push(
        [
          `    ${pattern})`,
          `      COMPREPLY=( $(compgen -f -- "$cur") )`,
          `      return 0`,
          `      ;;`,
        ].join("\n"),
      );
    }
  }

  for (const sub of spec.subcommands) {
    if (!sub.children || sub.children.length === 0) continue;
    const childWords = sub.children.map((c) => c.name).join(" ");
    cases.push(
      [
        `    ${sub.name})`,
        `      COMPREPLY=( $(compgen -W "${childWords}" -- "$cur") )`,
        `      return 0`,
        `      ;;`,
      ].join("\n"),
    );
  }

  return `# bash completion for ${program}
#
# Generated by \`${program} completions bash\`. Load it in your shell, e.g.:
#   ${program} completions bash > /usr/local/etc/bash_completion.d/${program}
# or source it directly from ~/.bashrc:
#   source <(${program} completions bash)

${posixListModelsFunction(program, listModelsFn)}

${funcName}() {
  local cur prev
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"

  case "$prev" in
${cases.join("\n")}
  esac

  if [[ "$cur" == -* ]]; then
    COMPREPLY=( $(compgen -W "${allFlagWords}" -- "$cur") )
  else
    COMPREPLY=( $(compgen -W "${topLevelWords}" -- "$cur") )
  fi
}

complete -F ${funcName} ${program}
`;
}

/** Zsh `_arguments` value-spec for one flag (empty string for bare switches). */
function zshArgSpec(flag: CompletionFlag): string {
  if (!flag.takesValue) return "";
  const hint = flag.valueHint ?? "value";
  if (flag.enumValues && flag.enumValues.length > 0) {
    return `:${hint}:(${flag.enumValues.join(" ")})`;
  }
  if (flag.valueHint === "model") {
    return `:model:->models`;
  }
  if (flag.valueHint === "path") {
    return `:path:_files -/`;
  }
  return `:${hint}:`;
}

/** Render the zsh completion script. */
function generateZshCompletions(spec: CompletionSpec): string {
  const program = spec.program;
  const funcName = `_${program}`;
  const listModelsFn = `_${program}_list_models`;

  const optionLines: string[] = [];
  for (const flag of spec.flags) {
    const desc = escapeZshSingleQuoted(flag.description);
    const argSpec = zshArgSpec(flag);
    optionLines.push(`    '${flag.long}[${desc}]${argSpec}'`);
    if (flag.short) {
      optionLines.push(`    '${flag.short}[${desc}]${argSpec}'`);
    }
  }

  const topLevelValues = spec.subcommands
    .map((s) => `'${s.name}[${escapeZshSingleQuoted(s.description)}]'`)
    .join(" ");

  // One arm per subcommand that has a fixed child list, so adding or removing
  // a command in the spec is the whole edit.
  const childArms = spec.subcommands
    .filter((sub) => sub.children && sub.children.length > 0)
    .map((sub) => {
      const values = (sub.children ?? [])
        .map((child) => `'${child.name}[${escapeZshSingleQuoted(child.description)}]'`)
        .join(" ");
      return [
        `        ${sub.name})`,
        `          _values '${sub.name} argument' ${values}`,
        `          ;;`,
      ].join("\n");
    })
    .join("\n");

  return `#compdef ${program}
#
# Generated by \`${program} completions zsh\`. Load it in your shell, e.g.:
#   ${program} completions zsh > "\${fpath[1]}/_${program}"
# or source it directly from ~/.zshrc:
#   source <(${program} completions zsh)

${posixListModelsFunction(program, listModelsFn)}

${funcName}() {
  local context state state_descr line
  typeset -A opt_args
  local -a models

  _arguments -C \\
${optionLines.join(" \\\n")} \\
    '1: :->cmds' \\
    '*:: :->args'

  case "$state" in
    models)
      models=(\${(f)"$(${listModelsFn})"})
      _describe -t models 'model' models
      ;;
    cmds)
      _values 'command' ${topLevelValues}
      ;;
    args)
      case "\${line[1]}" in
${childArms}
      esac
      ;;
  esac
}

${funcName} "$@"
`;
}

/** Render the fish completion script. */
function generateFishCompletions(spec: CompletionSpec): string {
  const program = spec.program;
  const listModelsFn = `__${program}_list_models`;

  const lines: string[] = [];
  lines.push(`# fish completion for ${program}`);
  lines.push(`#`);
  lines.push(`# Generated by \`${program} completions fish\`. Save it as:`);
  lines.push(`#   ~/.config/fish/completions/${program}.fish`);
  lines.push("");
  lines.push(`function ${listModelsFn}`);
  lines.push(`    if command -v timeout >/dev/null 2>&1`);
  lines.push(`        timeout 0.3 ${program} --list-models 2>/dev/null | awk 'NR>1{print $1}'`);
  lines.push(`    else`);
  lines.push(`        ${program} --list-models 2>/dev/null | awk 'NR>1{print $1}'`);
  lines.push(`    end`);
  lines.push(`end`);
  lines.push("");
  lines.push(`complete -c ${program} -f`);
  lines.push("");

  for (const sub of spec.subcommands) {
    const desc = escapeFishSingleQuoted(sub.description);
    lines.push(`complete -c ${program} -n '__fish_use_subcommand' -a '${sub.name}' -d '${desc}'`);
  }
  lines.push("");

  for (const sub of spec.subcommands) {
    if (!sub.children || sub.children.length === 0) continue;
    const childNames = sub.children.map((c) => c.name).join(" ");
    lines.push(
      `complete -c ${program} -n '__fish_seen_subcommand_from ${sub.name}' -a '${childNames}'`,
    );
  }
  lines.push("");

  for (const flag of spec.flags) {
    const longName = flag.long.replace(/^--/, "");
    const shortPart = flag.short ? ` -s ${flag.short.replace(/^-/, "")}` : "";
    const desc = escapeFishSingleQuoted(flag.description);

    if (!flag.takesValue) {
      lines.push(`complete -c ${program}${shortPart} -l ${longName} -d '${desc}'`);
      continue;
    }
    if (flag.enumValues && flag.enumValues.length > 0) {
      lines.push(
        `complete -c ${program}${shortPart} -l ${longName} -x -a '${flag.enumValues.join(" ")}' -d '${desc}'`,
      );
    } else if (flag.valueHint === "model") {
      lines.push(
        `complete -c ${program}${shortPart} -l ${longName} -x -a '(${listModelsFn})' -d '${desc}'`,
      );
    } else if (flag.valueHint === "path") {
      lines.push(`complete -c ${program}${shortPart} -l ${longName} -r -F -d '${desc}'`);
    } else {
      lines.push(`complete -c ${program}${shortPart} -l ${longName} -x -d '${desc}'`);
    }
  }

  return `${lines.join("\n")}\n`;
}
