/**
 * AGENT BLAME — reasoning-level provenance for agent-written code.
 *
 * `git blame` answers "who changed this line". When an agent wrote most of the
 * file, the useful question is *why*: which prompt was the agent answering,
 * which turn produced the line, and what evidence (files it read, pages it
 * fetched, commands it ran) informed that turn. This module records that trail
 * and reconstructs it per line.
 *
 * Storage is a sibling of `checkpoints.ts` and deliberately mirrors its shape —
 * an append-only JSONL manifest plus a content-addressed blob store, every
 * write serialized through one promise queue, the directory created lazily:
 *
 * ```text
 * <dir>/manifest.jsonl   append-only log of turn/evidence/mutation records
 * <dir>/blobs/<sha256>   content-addressed file snapshots
 * ```
 *
 * Each manifest line is one of:
 *
 * - `{ kind: "turn", id, prompt, startedAt }` — a user prompt. Everything
 *   recorded afterwards (until the next turn) is attributed to it.
 * - `{ kind: "evidence", turnId, toolName, subject, untrusted, timestamp }` —
 *   one non-mutating tool result that informed the turn. `untrusted` is true
 *   for the sources `taint.ts` treats as attacker-controlled (`fetch`,
 *   `websearch`, any MCP tool), which is what makes "this line was written
 *   right after a fetched page said X" auditable.
 * - `{ kind: "mutation", turnId, path, beforeBlob, afterBlob, timestamp }` —
 *   one file write, as a pair of content hashes.
 *
 * ## Why content blobs rather than diffs
 *
 * Line attribution has to replay a file's whole history exactly; a stored diff
 * would have to be re-applied and any drift (an edit made outside the agent, a
 * crash between records) would silently corrupt every later line's blame.
 * Content-addressed blobs make replay exact *and* cost about the same as diffs
 * in the common case: mutation N's `after` and mutation N+1's `before` are the
 * same bytes, so they share one blob, and reverting a file to an earlier state
 * costs nothing new. The real cost is one blob per distinct file state — see
 * `INTEGRATION-provenance.md` for the measured growth and a pruning policy.
 * {@link CreateProvenanceStoreOptions.maxContentBytes} caps the damage a single
 * huge file can do.
 *
 * ## What "attribution" means here
 *
 * {@link ProvenanceStore.blame} replays the recorded mutations for a path in
 * order, diffing each recorded state against the next with an LCS, and carries
 * each surviving line's attribution across unchanged regions. A line the agent
 * wrote in turn 3 and never touched again still reads "turn 3" after ten later
 * edits — that carry-across is the whole point. Lines that were already in the
 * file before the agent first touched it are attributed to nobody.
 *
 * This module intentionally touches nothing else in the CLI: it is wired up by
 * the caller. See `INTEGRATION-provenance.md` at the repo root for the exact
 * call sites in `runtime.ts`, `args.ts` and `main.ts`, none of which this file
 * modifies.
 *
 * @packageDocumentation
 */

import { createHash, randomUUID } from "node:crypto";
import { mkdir, readFile, rename, stat, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { defaultSubject } from "@arcturn/core";
import type { AgentEvent, AgentEventListener, Message } from "@arcturn/types";
import { oneLine } from "./format.js";
import { DEFAULT_TAINT_SOURCE_PREFIXES, DEFAULT_TAINT_SOURCES } from "./taint.js";

/* -------------------------------------------------------------------------- */
/* Manifest records                                                            */
/* -------------------------------------------------------------------------- */

/** A user prompt; everything recorded afterwards belongs to it. */
export interface ProvenanceTurnRecord {
  kind: "turn";
  /** Unique id, generated by {@link ProvenanceStore.beginTurn}. */
  id: string;
  /** The prompt the agent was answering, whitespace-collapsed and clipped. */
  prompt: string;
  /** Epoch milliseconds the turn began. */
  startedAt: number;
}

/** One tool result that informed a turn. */
export interface ProvenanceEvidenceRecord {
  kind: "evidence";
  /** Turn this evidence was gathered during. */
  turnId: string;
  /** Tool that produced it, e.g. `"read"`, `"fetch"`. */
  toolName: string;
  /** What it was about — a path, a URL, a command; `""` when unknown. */
  subject: string;
  /**
   * True when the content came from a source `taint.ts` treats as
   * attacker-controlled (`fetch`, `websearch`, any MCP tool). Rendered
   * distinctly by {@link formatBlame}: a line written under the influence of
   * untrusted evidence is the security-relevant case.
   */
  untrusted: boolean;
  timestamp: number;
}

/** One file write, as a pair of content hashes. */
export interface ProvenanceMutationRecord {
  kind: "mutation";
  /** Turn during which the file was written. */
  turnId: string;
  /** Absolute path written. */
  path: string;
  /** sha256 of the content just before the write, or `null` if it did not exist. */
  beforeBlob: string | null;
  /** sha256 of the content just after the write, or `null` when unrecorded. */
  afterBlob: string | null;
  /**
   * Present and `true` when the content exceeded
   * {@link CreateProvenanceStoreOptions.maxContentBytes} and was therefore not
   * stored. Blame cannot replay across such a mutation and says so.
   */
  oversize?: true;
  timestamp: number;
}

/** One line of the provenance manifest. */
export type ProvenanceManifestEntry =
  | ProvenanceTurnRecord
  | ProvenanceEvidenceRecord
  | ProvenanceMutationRecord;

/** Per-turn rollup returned by {@link ProvenanceStore.turns}. */
export interface ProvenanceTurnSummary {
  /** The turn's id. */
  id: string;
  /** 1-based position in the session, in manifest order. */
  index: number;
  /** The prompt the agent was answering. */
  prompt: string;
  startedAt: number;
  /** Mutations recorded during the turn. */
  mutationCount: number;
  /** Evidence records gathered during the turn. */
  evidenceCount: number;
  /** How many of those came from an untrusted source. */
  untrustedCount: number;
}

/* -------------------------------------------------------------------------- */
/* Blame                                                                       */
/* -------------------------------------------------------------------------- */

/** One line of a file, with the turn that wrote it (if any). */
export interface BlameLine {
  /** 1-based line number in the file's last recorded state. */
  line: number;
  /** The line's text, without its terminator. */
  text: string;
  /** Turn that introduced this exact line; absent for pre-existing lines. */
  turnId?: string;
  /** The prompt that turn was answering; absent for pre-existing lines. */
  prompt?: string;
  /** Epoch milliseconds the line was written; absent for pre-existing lines. */
  at?: number;
  /** 1-based session position of {@link BlameLine.turnId}, for display. */
  turnIndex?: number;
}

/* -------------------------------------------------------------------------- */
/* Store                                                                       */
/* -------------------------------------------------------------------------- */

/** Reasoning-level provenance store backing `arcturn blame`. */
export interface ProvenanceStore {
  /**
   * Record a new user prompt. Every evidence and mutation recorded afterwards
   * (until the next `beginTurn`) is attributed to it.
   *
   * @param prompt - The user's prompt. Whitespace is collapsed and the text is
   *   clipped to {@link MAX_PROMPT_CHARS} before storage.
   * @returns The new turn's id.
   */
  beginTurn(prompt: string): Promise<string>;

  /**
   * Record one tool result that informed the current turn.
   *
   * @param toolName - Tool that produced it, e.g. `"read"`.
   * @param subject - Path, URL or command it concerned.
   * @param untrusted - Whether the source is attacker-controlled; see
   *   {@link isUntrustedEvidenceSource}.
   */
  recordEvidence(toolName: string, subject: string, untrusted: boolean): Promise<void>;

  /**
   * Record one file write.
   *
   * @param path - Path written; resolved to absolute before storage.
   * @param before - Content immediately before the write, or `null` when the
   *   file did not exist.
   * @param after - Content immediately after the write.
   */
  recordMutation(path: string, before: string | null, after: string): Promise<void>;

  /** Every recorded turn, oldest first. */
  turns(): Promise<ProvenanceTurnSummary[]>;

  /**
   * Every evidence record, oldest first. Pass `turnId` to filter to one turn.
   *
   * @param turnId - Restrict to evidence gathered during this turn.
   */
  evidence(turnId?: string): Promise<ProvenanceEvidenceRecord[]>;

  /**
   * Attribute each line of `file`'s last recorded state to the turn that wrote
   * it.
   *
   * Replays every recorded mutation for the path in order, carrying each
   * line's attribution across the unchanged regions of successive states, so a
   * line written in an early turn and never touched again keeps that early
   * turn. Lines already present before the first recorded mutation are
   * attributed to nobody (no `turnId`).
   *
   * The result describes the last state this store *recorded*, which is not
   * necessarily what is on disk right now — an edit made outside the agent is,
   * by construction, not attributable.
   *
   * @param file - Path to blame; matched after resolving to absolute.
   * @returns One entry per line, or `[]` when the path has no recorded
   *   mutations (or its history is unrecoverable, e.g. an oversize write).
   */
  blame(file: string): Promise<BlameLine[]>;

  /** Flush every queued write. Safe to call more than once. */
  close(): Promise<void>;
}

/** Options for {@link createProvenanceStore}. */
export interface CreateProvenanceStoreOptions {
  /**
   * Largest file content stored per mutation, in bytes (default 1 MiB).
   * Beyond it the record is kept but its blobs are not, so one generated
   * bundle cannot balloon the store. Blame reports such a file as
   * unattributable rather than guessing.
   */
  readonly maxContentBytes?: number;
}

/** Default for {@link CreateProvenanceStoreOptions.maxContentBytes}. */
export const DEFAULT_MAX_CONTENT_BYTES = 1024 * 1024;

/** Prompts longer than this are clipped before storage. */
export const MAX_PROMPT_CHARS = 200;

const MANIFEST_FILE = "manifest.jsonl";
/**
 * Paths whose CONTENT is never copied into the store.
 *
 * The store keeps full file content so `blame` can attribute lines — which
 * would otherwise make `~/.arcturn/provenance` a durable copy of every secret the
 * agent touched, with no purge. Matching files are still recorded as
 * mutations (you can see that a turn changed `.env`), just without bytes.
 */
const SECRET_PATH_PATTERNS: readonly RegExp[] = [
  /(^|\/)\.env(\.|$)/,
  /(^|\/)\.npmrc$/,
  /(^|\/)id_(rsa|ed25519|ecdsa)$/,
  /\.(pem|key|p12|pfx)$/,
  /(^|\/)credentials$/,
  /(^|\/)\.aws\//,
];

/**
 * Whether a path's content must be withheld from the provenance store.
 *
 * @param path - Absolute or relative path being recorded.
 */
export function isSecretPath(path: string): boolean {
  const normalized = path.split("\\").join("/");
  return SECRET_PATH_PATTERNS.some((pattern) => pattern.test(normalized));
}

const BLOBS_DIR = "blobs";

/** Tools whose calls are mutations rather than evidence. */
export const MUTATION_TOOL_NAMES: readonly string[] = ["write", "edit"];

function isMissing(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    (error as NodeJS.ErrnoException).code === "ENOENT"
  );
}

function tryParseLine(line: string): ProvenanceManifestEntry | undefined {
  try {
    return JSON.parse(line) as ProvenanceManifestEntry;
  } catch {
    return undefined;
  }
}

/**
 * File-backed {@link ProvenanceStore}.
 *
 * Every manifest append and blob write goes through one promise queue — the
 * same discipline `FileCheckpointStore` and `JsonlSessionStore` use — so
 * concurrent `recordMutation()` calls can never interleave into a torn line,
 * and the manifest order always matches the order the calls were made in.
 * Blobs are written to a temp name and renamed, so a crash mid-write can never
 * leave a blob whose content does not match its hash.
 */
class FileProvenanceStore implements ProvenanceStore {
  readonly #dir: string;
  readonly #maxContentBytes: number;
  /** Serializes every manifest append and blob write. */
  #queue: Promise<unknown> = Promise.resolve();
  #currentTurnId: string | undefined;
  #dirReady: Promise<void> | undefined;

  constructor(dir: string, options: CreateProvenanceStoreOptions) {
    this.#dir = dir;
    this.#maxContentBytes = options.maxContentBytes ?? DEFAULT_MAX_CONTENT_BYTES;
  }

  async beginTurn(prompt: string): Promise<string> {
    const id = randomUUID();
    const startedAt = Date.now();
    const text = oneLine(prompt, MAX_PROMPT_CHARS);
    await this.#enqueue(async () => {
      this.#currentTurnId = id;
      await this.#append({
        kind: "turn",
        id,
        prompt: text.length === 0 ? "(empty prompt)" : text,
        startedAt,
      });
    });
    return id;
  }

  async recordEvidence(toolName: string, subject: string, untrusted: boolean): Promise<void> {
    const turnId = await this.#turnId();
    const timestamp = Date.now();
    await this.#enqueue(async () => {
      await this.#append({
        kind: "evidence",
        turnId,
        toolName,
        subject,
        untrusted,
        timestamp,
      });
    });
  }

  async recordMutation(path: string, before: string | null, after: string): Promise<void> {
    // Content for secret-looking paths is never persisted: the store would
    // otherwise become a durable copy of every credential the agent touched,
    // with no purge. The mutation itself is still recorded.
    if (isSecretPath(path)) {
      return this.#recordRedactedMutation(path);
    }
    const turnId = await this.#turnId();
    const absolute = resolve(path);
    const timestamp = Date.now();
    await this.#enqueue(async () => {
      const oversize =
        Buffer.byteLength(after, "utf8") > this.#maxContentBytes ||
        (before !== null && Buffer.byteLength(before, "utf8") > this.#maxContentBytes);
      if (oversize) {
        await this.#append({
          kind: "mutation",
          turnId,
          path: absolute,
          beforeBlob: null,
          afterBlob: null,
          oversize: true,
          timestamp,
        });
        return;
      }
      const beforeBlob = before === null ? null : await this.#putBlob(before);
      const afterBlob = await this.#putBlob(after);
      await this.#append({
        kind: "mutation",
        turnId,
        path: absolute,
        beforeBlob,
        afterBlob,
        timestamp,
      });
    });
  }

  async turns(): Promise<ProvenanceTurnSummary[]> {
    const entries = await this.#readManifest();
    const summaries: ProvenanceTurnSummary[] = [];
    const byId = new Map<string, ProvenanceTurnSummary>();
    for (const entry of entries) {
      if (entry.kind === "turn") {
        const summary: ProvenanceTurnSummary = {
          id: entry.id,
          index: summaries.length + 1,
          prompt: entry.prompt,
          startedAt: entry.startedAt,
          mutationCount: 0,
          evidenceCount: 0,
          untrustedCount: 0,
        };
        summaries.push(summary);
        byId.set(entry.id, summary);
        continue;
      }
      // Attribute by the record's own turnId, not by position: a record whose
      // turn is unknown (a tampered or truncated manifest) is simply dropped
      // from the rollup rather than mis-credited to the preceding turn.
      const summary = byId.get(entry.turnId);
      if (!summary) continue;
      if (entry.kind === "mutation") {
        summary.mutationCount += 1;
      } else {
        summary.evidenceCount += 1;
        if (entry.untrusted) summary.untrustedCount += 1;
      }
    }
    return summaries;
  }

  async evidence(turnId?: string): Promise<ProvenanceEvidenceRecord[]> {
    const entries = await this.#readManifest();
    return entries.filter(
      (entry): entry is ProvenanceEvidenceRecord =>
        entry.kind === "evidence" && (turnId === undefined || entry.turnId === turnId),
    );
  }

  async blame(file: string): Promise<BlameLine[]> {
    const absolute = resolve(file);
    const entries = await this.#readManifest();

    const turns = new Map<string, { prompt: string; index: number }>();
    let index = 0;
    for (const entry of entries) {
      if (entry.kind !== "turn") continue;
      index += 1;
      turns.set(entry.id, { prompt: entry.prompt, index });
    }

    const mutations = entries.filter(
      (entry): entry is ProvenanceMutationRecord =>
        entry.kind === "mutation" && entry.path === absolute,
    );
    if (mutations.length === 0) return [];

    /** Current file state; `undefined` means "unrecoverable, resync needed". */
    let state: AttributedLine[] | undefined;

    for (const mutation of mutations) {
      if (mutation.oversize === true || mutation.afterBlob === null) {
        state = undefined;
        continue;
      }
      const after = await this.#getBlob(mutation.afterBlob);
      if (after === undefined) {
        state = undefined;
        continue;
      }
      let before: string | null = null;
      if (mutation.beforeBlob !== null) {
        const content = await this.#getBlob(mutation.beforeBlob);
        if (content === undefined) {
          // The pre-image blob is gone (pruned, or a partial store): its lines
          // cannot be told apart from the ones this turn wrote, and crediting
          // them all to this turn would be a lie. Give up on the replay.
          state = undefined;
          continue;
        }
        before = content;
      }

      // The recorded pre-image is authoritative. When it disagrees with the
      // state replayed so far — a file deleted and recreated behind our back,
      // a gap in the manifest — resync to it with those lines unattributed,
      // rather than carrying stale attributions forward.
      const recorded = unattributed(before);
      const start = state !== undefined && sameText(state, recorded) ? state : recorded;

      state = applyMutation(start, after.split("\n"), mutation);
    }

    if (state === undefined) return [];

    return state.map((entry, i) => {
      const meta = entry.turnId === undefined ? undefined : turns.get(entry.turnId);
      return {
        line: i + 1,
        text: entry.text,
        ...(entry.turnId === undefined ? {} : { turnId: entry.turnId }),
        ...(meta === undefined ? {} : { prompt: meta.prompt, turnIndex: meta.index }),
        ...(entry.at === undefined ? {} : { at: entry.at }),
      } satisfies BlameLine;
    });
  }

  async close(): Promise<void> {
    await this.#queue.catch(() => undefined);
  }

  /** The active turn, opening an untracked one when nothing began a turn yet. */
  async #turnId(): Promise<string> {
    // Mirrors `FileCheckpointStore.snapshot`: dropping a record because no
    // turn was open would lose provenance forever, so an untracked turn is
    // opened instead and the trail stays complete.
    return this.#currentTurnId ?? (await this.beginTurn("(untracked)"));
  }

  /**
   * Record that a secret-looking path changed, without its content.
   *
   * `blame` will show the file as touched by the turn but cannot attribute
   * lines — the honest trade for not persisting credentials.
   */
  async #recordRedactedMutation(path: string): Promise<void> {
    const turnId = await this.#turnId();
    const absolute = resolve(path);
    const timestamp = Date.now();
    await this.#enqueue(async () => {
      await this.#append({
        kind: "mutation",
        turnId,
        path: absolute,
        beforeBlob: null,
        afterBlob: null,
        oversize: true,
        timestamp,
      });
    });
  }

  /** Store `content` under its sha256 and return the digest. */
  async #putBlob(content: string): Promise<string> {
    const buffer = Buffer.from(content, "utf8");
    const sha = createHash("sha256").update(buffer).digest("hex");
    const path = this.#blobPath(sha);
    try {
      await stat(path);
      return sha; // Already stored under this content hash.
    } catch {
      // Fall through and write it.
    }
    await mkdir(this.#blobsDir(), { recursive: true });
    const tmp = join(this.#blobsDir(), `.tmp-${randomUUID()}`);
    await writeFile(tmp, buffer);
    await rename(tmp, path);
    return sha;
  }

  /** Read a blob, or `undefined` when it is missing (e.g. pruned). */
  async #getBlob(sha: string): Promise<string | undefined> {
    try {
      return await readFile(this.#blobPath(sha), "utf8");
    } catch {
      return undefined;
    }
  }

  async #append(entry: ProvenanceManifestEntry): Promise<void> {
    await this.#ensureDir();
    await writeFile(this.#manifestPath(), `${JSON.stringify(entry)}\n`, { flag: "a" });
  }

  async #readManifest(): Promise<ProvenanceManifestEntry[]> {
    let raw: string;
    try {
      raw = await readFile(this.#manifestPath(), "utf8");
    } catch (error) {
      if (isMissing(error)) return [];
      throw error;
    }
    const entries: ProvenanceManifestEntry[] = [];
    for (const line of raw.split("\n")) {
      if (line.trim().length === 0) continue;
      const parsed = tryParseLine(line);
      if (parsed !== undefined) entries.push(parsed);
    }
    return entries;
  }

  #manifestPath(): string {
    return join(this.#dir, MANIFEST_FILE);
  }

  #blobsDir(): string {
    return join(this.#dir, BLOBS_DIR);
  }

  #blobPath(sha: string): string {
    // A manifest is data, not trust. Without this an `afterBlob` of
    // "../../../id_rsa" would make `arcturn blame` an arbitrary-file-read
    // primitive that prints the file as the blamed content.
    if (!/^[0-9a-f]{64}$/.test(sha)) {
      throw new Error(`provenance: blob id is not a sha256 digest: ${JSON.stringify(sha)}`);
    }
    return join(this.#blobsDir(), sha);
  }

  async #ensureDir(): Promise<void> {
    this.#dirReady ??= mkdir(this.#dir, { recursive: true }).then(() => undefined);
    await this.#dirReady;
  }

  /** Chain `fn` onto the write queue so it never overlaps another queued op. */
  #enqueue<T>(fn: () => Promise<T>): Promise<T> {
    const result = this.#queue.catch(() => undefined).then(fn);
    this.#queue = result.catch(() => undefined);
    return result;
  }
}

/** A line plus the turn that introduced it, used while replaying a file. */
interface AttributedLine {
  text: string;
  turnId?: string;
  at?: number;
}

/** Split `text` into lines nobody is credited for. `null` means "no file". */
function unattributed(text: string | null): AttributedLine[] {
  if (text === null) return [];
  return text.split("\n").map((line) => ({ text: line }));
}

/** Whether two states hold exactly the same lines (length included). */
function sameText(a: readonly AttributedLine[], b: readonly AttributedLine[]): boolean {
  if (a.length !== b.length) return false;
  return a.every((line, i) => line.text === b[i]?.text);
}

/** Diff `state` against `afterLines`, carrying attribution across equal lines. */
function applyMutation(
  state: readonly AttributedLine[],
  afterLines: readonly string[],
  mutation: ProvenanceMutationRecord,
): AttributedLine[] {
  const ops = diffLineOps(
    state.map((line) => line.text),
    afterLines,
  );
  const next: AttributedLine[] = [];
  for (const op of ops) {
    if (op.type === "equal") {
      // The carry-across that makes blame useful: an untouched line keeps the
      // turn that first wrote it, however many later edits pass over the file.
      next.push(state[op.oldIndex] as AttributedLine);
    } else if (op.type === "add") {
      next.push({
        text: afterLines[op.newIndex] as string,
        turnId: mutation.turnId,
        at: mutation.timestamp,
      });
    }
  }
  return next;
}

/**
 * Create a {@link ProvenanceStore} backed by `dir`.
 *
 * The directory (and its `blobs/` subdirectory) is created lazily on the first
 * write; `dir` should be unique per session, e.g.
 * `~/.arcturn/provenance/<sessionId>`.
 *
 * @param dir - Directory to store the manifest and blobs in.
 * @param options - Content-size cap.
 */
export function createProvenanceStore(
  dir: string,
  options: CreateProvenanceStoreOptions = {},
): ProvenanceStore {
  return new FileProvenanceStore(dir, options);
}

/* -------------------------------------------------------------------------- */
/* Line diff                                                                   */
/* -------------------------------------------------------------------------- */

/** One step of a line-level diff, carrying the indices rather than the text. */
export type LineOp =
  | { type: "equal"; oldIndex: number; newIndex: number }
  | { type: "del"; oldIndex: number }
  | { type: "add"; newIndex: number };

/** Cells above this are treated as "too large" for the O(n*m) LCS table. */
const MAX_LCS_CELLS = 4_000_000;

/**
 * Line-level LCS diff, reporting indices instead of text.
 *
 * `packages/tools/src/diff.ts` has the same DP core but only exports
 * {@link createUnifiedDiff}, which returns *formatted* text with three lines of
 * context — attribution needs every line's fate, including the untouched ones
 * a unified diff omits, so the walk is reimplemented here rather than parsed
 * back out of a rendered diff.
 *
 * Above {@link MAX_LCS_CELLS} cells it degrades to "everything replaced",
 * exactly as `diff.ts` does: blame then credits the whole file to the writing
 * turn, which is coarse but never wrong about who touched it.
 *
 * @param oldLines - Lines before the change.
 * @param newLines - Lines after the change.
 * @returns Ops in file order; `equal` carries both indices.
 */
export function diffLineOps(oldLines: readonly string[], newLines: readonly string[]): LineOp[] {
  const n = oldLines.length;
  const m = newLines.length;
  const ops: LineOp[] = [];

  if (n * m > MAX_LCS_CELLS) {
    for (let i = 0; i < n; i++) ops.push({ type: "del", oldIndex: i });
    for (let j = 0; j < m; j++) ops.push({ type: "add", newIndex: j });
    return ops;
  }

  // dp[i][j] = length of the LCS of oldLines[i..] and newLines[j..]
  const dp: Uint32Array[] = [];
  for (let i = 0; i <= n; i++) dp.push(new Uint32Array(m + 1));
  for (let i = n - 1; i >= 0; i--) {
    const dpi = dp[i] as Uint32Array;
    const dpi1 = dp[i + 1] as Uint32Array;
    const oldLine = oldLines[i] as string;
    for (let j = m - 1; j >= 0; j--) {
      dpi[j] =
        oldLine === newLines[j]
          ? (dpi1[j + 1] as number) + 1
          : Math.max(dpi1[j] as number, dpi[j + 1] as number);
    }
  }

  let i = 0;
  let j = 0;
  while (i < n && j < m) {
    if (oldLines[i] === newLines[j]) {
      ops.push({ type: "equal", oldIndex: i, newIndex: j });
      i++;
      j++;
    } else if ((dp[i + 1] as Uint32Array)[j]! >= (dp[i] as Uint32Array)[j + 1]!) {
      ops.push({ type: "del", oldIndex: i });
      i++;
    } else {
      ops.push({ type: "add", newIndex: j });
      j++;
    }
  }
  while (i < n) ops.push({ type: "del", oldIndex: i++ });
  while (j < m) ops.push({ type: "add", newIndex: j++ });
  return ops;
}

/* -------------------------------------------------------------------------- */
/* Observer                                                                    */
/* -------------------------------------------------------------------------- */

/**
 * Whether a tool's output is attacker-controlled.
 *
 * Reuses `taint.ts`'s source lists verbatim (`fetch`, `websearch`, and any
 * tool whose name starts with `mcp`) so "untrusted" means exactly the same
 * thing in the provenance trail as it does to the taint tracker.
 *
 * @param toolName - Tool that produced the result.
 */
export function isUntrustedEvidenceSource(toolName: string): boolean {
  if (DEFAULT_TAINT_SOURCES.includes(toolName)) return true;
  const lower = toolName.toLowerCase();
  return DEFAULT_TAINT_SOURCE_PREFIXES.some(
    (prefix) => prefix.length > 0 && lower.startsWith(prefix.toLowerCase()),
  );
}

/** Reads a file's current content; `null` when it does not exist. */
export type ProvenanceFileReader = (path: string) => Promise<string | null>;

/**
 * An {@link AgentEventListener} that also lets a caller await its in-flight
 * work — the event stream is synchronous but reading the file a tool just
 * wrote is not.
 */
export type ProvenanceObserver = AgentEventListener & {
  /** Resolve once every mutation implied by the events so far is recorded. */
  flush(): Promise<void>;
};

/** Extract the plain text of a user prompt message. */
function promptText(message: Message): string {
  if (message.role !== "user") return "";
  return message.content
    .map((block) => (block.type === "text" ? block.text : ""))
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
}

function detailString(
  details: Record<string, unknown> | undefined,
  key: string,
): string | undefined {
  const value = details?.[key];
  return typeof value === "string" ? value : undefined;
}

/**
 * Rebuild a file's pre-image from its post-image and the unified diff the
 * `edit` tool reported.
 *
 * The diff's hunk headers give the new-file line numbers, so everything
 * outside a hunk is identical in both versions and everything inside one is
 * replayed backwards (` ` and `-` lines belong to the old file, `+` lines do
 * not). Exact, and — unlike reading the file a second time — immune to the
 * race between the tool's write and the observer's read.
 *
 * @param after - The file's content after the edit.
 * @param diff - The unified diff from `EditToolDetails.diff`.
 * @returns The pre-edit content, or `undefined` when the diff is unparseable.
 */
export function reconstructBefore(after: string, diff: string): string | undefined {
  const afterLines = after.split("\n");
  const diffLines = diff.split("\n");
  const out: string[] = [];
  let newIndex = 0;
  let sawHunk = false;
  let inHunk = false;

  for (const line of diffLines) {
    const header = /^@@ -\d+(?:,\d+)? \+(\d+)(?:,\d+)? @@/.exec(line);
    if (header) {
      const start = Number(header[1]) - 1;
      if (start < newIndex || start > afterLines.length) return undefined;
      for (let i = newIndex; i < start; i++) out.push(afterLines[i] as string);
      newIndex = start;
      sawHunk = true;
      inHunk = true;
      continue;
    }
    if (!inHunk) continue; // `--- a/x` / `+++ b/x` headers, before any hunk.
    const marker = line[0];
    const text = line.slice(1);
    if (marker === " ") {
      if (afterLines[newIndex] !== text) return undefined;
      out.push(text);
      newIndex += 1;
    } else if (marker === "-") {
      out.push(text);
    } else if (marker === "+") {
      if (afterLines[newIndex] !== text) return undefined;
      newIndex += 1;
    } else {
      return undefined;
    }
  }
  if (!sawHunk) return undefined;
  for (let i = newIndex; i < afterLines.length; i++) out.push(afterLines[i] as string);
  return out.join("\n");
}

/**
 * Build an `AgentEvent` listener that drives a {@link ProvenanceStore}.
 *
 * - `runStart` opens a turn named by the user's prompt.
 * - every successful non-mutating tool call becomes one evidence record,
 *   tagged untrusted per {@link isUntrustedEvidenceSource}.
 * - every successful `write`/`edit` becomes one mutation record. The
 *   post-image comes from `readFile` (the tool has already written it by the
 *   time `toolEnd` fires); the pre-image comes from `WriteToolDetails.created`
 *   (`true` ⇒ the file did not exist) or, for `edit`, from replaying
 *   `EditToolDetails.diff` backwards over the post-image, falling back to the
 *   post-image this observer last recorded for the path.
 *
 * All disk work is chained onto one internal queue, so mutations are recorded
 * in event order even though the listener itself must return synchronously,
 * and a failure anywhere is swallowed: provenance must never break a run.
 *
 * `subagentEvent` is deliberately not unwrapped — mirroring `auditObserver`,
 * the runtime subscribes each sub-agent's own stream, so unwrapping here would
 * record every delegated write twice.
 *
 * @param store - Destination provenance store.
 * @param readFile - Reads a file's current content; `null` when absent.
 * @returns A listener with an extra `flush()` for tests and shutdown.
 */
export function provenanceObserver(
  store: ProvenanceStore,
  readFile: ProvenanceFileReader,
): ProvenanceObserver {
  const pending = new Map<string, { toolName: string; input: Record<string, unknown> }>();
  /** Last post-image this observer recorded, per path — the pre-image fallback. */
  const lastAfter = new Map<string, string>();
  let queue: Promise<unknown> = Promise.resolve();

  const enqueue = (fn: () => Promise<unknown>): void => {
    queue = queue
      .catch(() => undefined)
      .then(fn)
      .catch(() => undefined);
  };

  const observe = (event: AgentEvent): void => {
    switch (event.type) {
      case "runStart": {
        // Queued, not fired directly: the previous turn's mutation may still
        // be reading its file, and opening the next turn ahead of it would
        // credit that turn with work the previous prompt asked for.
        enqueue(() => store.beginTurn(promptText(event.prompt)));
        return;
      }
      case "toolStart": {
        pending.set(event.toolCallId, { toolName: event.toolName, input: event.input });
        return;
      }
      case "toolEnd": {
        const started = pending.get(event.toolCallId);
        pending.delete(event.toolCallId);
        const toolName = started?.toolName ?? event.result.toolName;
        if (event.result.isError) return; // A failed call informed nothing and wrote nothing.

        if (!MUTATION_TOOL_NAMES.includes(toolName)) {
          const subject = started ? defaultSubject(toolName, started.input) : "";
          enqueue(() =>
            store.recordEvidence(toolName, subject, isUntrustedEvidenceSource(toolName)),
          );
          return;
        }

        const details = event.result.details;
        const path = detailString(details, "path");
        if (path === undefined) return;
        const created = details?.created === true;
        const diff = detailString(details, "diff");

        // Start the read NOW, not when the queue drains: `toolEnd` is the last
        // moment the file is known to hold what this call wrote, and a later
        // tool call could otherwise overwrite it before the queue got there —
        // which would silently record the wrong post-image.
        const afterRead = readFile(path).catch(() => null);

        enqueue(async () => {
          const after = await afterRead;
          if (after === null) return; // Written then removed before we looked.
          let before: string | null;
          if (created) {
            // Authoritative, and the only correct answer for a recreate: the
            // file did not exist, so no line predates this turn.
            before = null;
          } else {
            before =
              (diff === undefined ? undefined : reconstructBefore(after, diff)) ??
              lastAfter.get(path) ??
              null;
          }
          lastAfter.set(path, after);
          await store.recordMutation(path, before, after);
        });
        return;
      }
      default:
        return;
    }
  };

  return Object.assign(observe, {
    async flush(): Promise<void> {
      await queue.catch(() => undefined);
      await store.close();
    },
  });
}

/* -------------------------------------------------------------------------- */
/* Rendering                                                                   */
/* -------------------------------------------------------------------------- */

/** Options for {@link formatBlame}. */
export interface FormatBlameOptions {
  /** Group by turn instead of printing every line (the `--summary` mode). */
  summary?: boolean;
  /**
   * Evidence records for the session. When given, a footer lists what informed
   * each turn that appears in the output, marking untrusted sources.
   */
  evidence?: readonly ProvenanceEvidenceRecord[];
  /** Maximum characters of a prompt shown per row (default `32`). */
  maxPromptWidth?: number;
  /** Path shown in the summary heading; omitted when absent. */
  path?: string;
}

/** The column shown for a line nobody is credited for. */
const NO_TURN = "-";

/** Suffix marking evidence from an attacker-controlled source. */
const UNTRUSTED_MARK = "[untrusted]";

function padEnd(value: string, width: number): string {
  return value.length >= width ? value : value + " ".repeat(width - value.length);
}

function padStart(value: string, width: number): string {
  return value.length >= width ? value : " ".repeat(width - value.length) + value;
}

function turnLabel(line: BlameLine): string {
  return line.turnIndex === undefined ? NO_TURN : `turn ${line.turnIndex}`;
}

function promptLabel(line: BlameLine, width: number): string {
  return line.prompt === undefined ? NO_TURN : `"${oneLine(line.prompt, width)}"`;
}

/**
 * Build the evidence footer: what informed each turn present in `lines`.
 *
 * Untrusted rows are prefixed with `!` and suffixed with `[untrusted]`, so a
 * reader scanning the footer sees at a glance that a fetched page or an MCP
 * server was in the room when these lines were written.
 */
function evidenceFooter(
  lines: readonly BlameLine[],
  evidence: readonly ProvenanceEvidenceRecord[],
): string[] {
  const shown = new Map<string, { index: number; prompt: string }>();
  for (const line of lines) {
    if (line.turnId === undefined || line.turnIndex === undefined) continue;
    if (!shown.has(line.turnId)) {
      shown.set(line.turnId, { index: line.turnIndex, prompt: line.prompt ?? "" });
    }
  }
  if (shown.size === 0) return [];

  const out: string[] = ["", "Evidence"];
  const ordered = [...shown.entries()].sort((a, b) => a[1].index - b[1].index);
  for (const [turnId, meta] of ordered) {
    const rows = evidence.filter((entry) => entry.turnId === turnId);
    out.push(`  turn ${meta.index}  "${oneLine(meta.prompt, 60)}"`);
    if (rows.length === 0) {
      out.push("    (no evidence recorded)");
      continue;
    }
    for (const row of rows) {
      const subject = row.subject === "" ? "" : `  ${oneLine(row.subject, 80)}`;
      out.push(
        row.untrusted
          ? `  ! ${row.toolName}${subject}  ${UNTRUSTED_MARK}`
          : `    ${row.toolName}${subject}`,
      );
    }
  }

  const untrusted = evidence.filter((entry) => entry.untrusted && shown.has(entry.turnId)).length;
  if (untrusted > 0) {
    out.push("");
    out.push(
      `${untrusted} untrusted source${untrusted === 1 ? "" : "s"} informed the turns above — ` +
        "content from the web or an MCP server is data, not instructions.",
    );
  }
  return out;
}

/**
 * Render blame lines for a terminal.
 *
 * Detail mode prints one row per line —
 * `12  turn 3  "fix the session bug"  const x = 1` — with pre-existing lines
 * showing `-` in both attribution columns. Summary mode replaces the rows with
 * a per-turn tally, newest turn first. Both modes append the evidence footer
 * when {@link FormatBlameOptions.evidence} is supplied.
 *
 * @param lines - Output of {@link ProvenanceStore.blame}.
 * @param options - Mode, evidence, and column widths.
 * @returns Lines to print; join with `"\n"`.
 */
export function formatBlame(
  lines: readonly BlameLine[],
  options: FormatBlameOptions = {},
): string[] {
  const promptWidth = options.maxPromptWidth ?? 32;
  if (lines.length === 0) {
    return ["no provenance recorded for this file"];
  }

  const out: string[] = [];

  if (options.summary === true) {
    if (options.path !== undefined) out.push(options.path);
    const groups = new Map<string, { index: number; prompt: string; count: number }>();
    let unattributedCount = 0;
    for (const line of lines) {
      if (line.turnId === undefined) {
        unattributedCount += 1;
        continue;
      }
      const group = groups.get(line.turnId);
      if (group) {
        group.count += 1;
        continue;
      }
      groups.set(line.turnId, {
        index: line.turnIndex ?? 0,
        prompt: line.prompt ?? "",
        count: 1,
      });
    }
    const ordered = [...groups.values()].sort((a, b) => b.index - a.index);
    const labelWidth = Math.max(
      ...ordered.map((group) => `turn ${group.index}`.length),
      "(pre-existing)".length,
    );
    for (const group of ordered) {
      out.push(
        `${padEnd(`turn ${group.index}`, labelWidth)}  ` +
          `${padEnd(`"${oneLine(group.prompt, promptWidth)}"`, promptWidth + 2)}  ` +
          `${padStart(String(group.count), 5)} line${group.count === 1 ? "" : "s"}`,
      );
    }
    if (unattributedCount > 0) {
      out.push(
        `${padEnd("(pre-existing)", labelWidth)}  ${padEnd("", promptWidth + 2)}  ` +
          `${padStart(String(unattributedCount), 5)} line${unattributedCount === 1 ? "" : "s"}`,
      );
    }
  } else {
    const numberWidth = String(lines.length).length;
    const turnWidth = Math.max(...lines.map((line) => turnLabel(line).length));
    const promptColumn = Math.max(...lines.map((line) => promptLabel(line, promptWidth).length));
    for (const line of lines) {
      out.push(
        `${padStart(String(line.line), numberWidth)}  ` +
          `${padEnd(turnLabel(line), turnWidth)}  ` +
          `${padEnd(promptLabel(line, promptWidth), promptColumn)}  ` +
          line.text,
      );
    }
  }

  if (options.evidence !== undefined) out.push(...evidenceFooter(lines, options.evidence));
  return out;
}
