/**
 * Everything the integration suite needs on disk before VS Code is launched.
 *
 * Nothing here is a mock of the `vscode` API — that is the whole point of the
 * integration suite. What *is* faked is the one thing a CI machine and this
 * laptop are equally unlikely to have: a real `arcturn` binary. In its place
 * we write a small program that records how it was invoked and, in TUI mode,
 * records the raw bytes typed into its terminal. That recording is the only
 * reason the security test below can make a claim at all: VS Code's stable
 * API gives an extension no way to read back what `Terminal.sendText` sent,
 * so the observation has to happen at the other end of the pty.
 *
 * Everything is written under `.vscode-test/fixtures`, which is wiped on every
 * run. In particular the workspace VS Code opens is *generated*, never a
 * directory in the repository — one of the files in it is deliberately named
 * to be hostile to a shell, and that is not a thing to leave lying around in
 * a source tree.
 */

import { chmodSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

/**
 * Where the isolated VS Code profiles live.
 *
 * Not under `.vscode-test/` with everything else, and the reason is specific:
 * VS Code puts its main IPC socket inside `--user-data-dir`, and a unix domain
 * socket path cannot exceed 103 characters. A checkout a few directories deep
 * blows that budget on its own, and the failure is an opaque `ENOTSOCK` from
 * Electron with the tests never starting. A short path costs nothing and
 * removes a class of "works on my machine".
 */
const PROFILE_ROOT =
  process.platform === "win32" ? join(tmpdir(), "arcturn-vscode-it") : "/tmp/arcturn-vscode-it";

/**
 * A filename built to execute a command if it were ever pasted at a shell
 * prompt bare: the quote ends whatever word it landed in, the semicolons end
 * the statement, and `touch pwned` is the observable side effect.
 *
 * The extension is expected to refuse to mention this file at all — see
 * `mentions.ts`, which allow-lists characters and rejects rather than repairs.
 * The test watches that refusal happen in a real editor.
 */
export const HOSTILE_FILENAME = 'ev"il;touch pwned;#.ts';

/** A name that is harmless but shell-special, so the mention must be quoted. */
export const QUOTED_FILENAME = "probe (1).ts";

/** A name that needs neither quoting nor refusing. */
export const PLAIN_FILENAME = "probe-target.ts";

/** The marker `HOSTILE_FILENAME` would create if the injection ever ran. */
export const INJECTION_MARKER = "pwned";

const PROBE_SOURCE = [
  "export function one(): number {",
  "  return 1;",
  "}",
  "",
  "export function two(): number {",
  "  return 2;",
  "}",
  "",
].join("\n");

/**
 * The stand-in engine, as a Node program.
 *
 * Three modes, matching the three ways the extension invokes the binary:
 *
 * - `--version` — what `cli.ts` probes with `execFile` before it will drive
 *   the engine. Answering `0.2.0` keeps the upgrade nag out of the run.
 * - `serve …` — what the sidebar spawns. It records the argument vector and
 *   exits without announcing an address, which is a failure the supervisor is
 *   documented to turn into a reconnect card. The *record* is the point: it is
 *   how the suite proves a spawn did, or did not, happen.
 * - anything else — the TUI. It puts the tty in raw mode and appends every
 *   byte it receives to a log, so the suite can read back exactly what the
 *   extension typed into a real VS Code terminal.
 */
function fakeCliSource(spawnLog, ttyLog) {
  return `// Generated by test/support/fixtures.mjs. Not a real engine.
const { appendFileSync } = require("node:fs");

const SPAWN_LOG = ${JSON.stringify(spawnLog)};
const TTY_LOG = ${JSON.stringify(ttyLog)};
const argv = process.argv.slice(2);

appendFileSync(SPAWN_LOG, JSON.stringify({ at: Date.now(), argv }) + "\\n");

if (argv[0] === "--version") {
  process.stdout.write("0.2.0\\n");
  process.exit(0);
}

if (argv[0] === "serve") {
  process.stderr.write("fake arcturn: this build does not serve\\n");
  process.exit(3);
}

process.stdout.write("fake arcturn TUI: reading raw stdin\\r\\n");
try {
  if (process.stdin.isTTY) process.stdin.setRawMode(true);
} catch {
  // Not a tty (should not happen inside a VS Code terminal); cooked mode still
  // records, just a line at a time.
}
process.stdin.on("data", (chunk) => appendFileSync(TTY_LOG, chunk));
process.stdin.on("end", () => process.exit(0));
process.stdin.resume();
// Keep the event loop alive so the terminal stays "the engine's".
setInterval(() => {}, 1 << 30);
`;
}

function writeWorkspaceSettings(dir, settings) {
  mkdirSync(join(dir, ".vscode"), { recursive: true });
  writeFileSync(join(dir, ".vscode", "settings.json"), `${JSON.stringify(settings, null, 2)}\n`);
}

/**
 * Build the fixture tree and return every path the config and the tests need.
 *
 * @param {string} extensionRoot - `editors/vscode`, the directory holding the
 *   extension manifest.
 */
export function buildFixtures(extensionRoot) {
  const root = join(extensionRoot, ".vscode-test", "fixtures");
  rmSync(root, { recursive: true, force: true });
  rmSync(PROFILE_ROOT, { recursive: true, force: true });

  const bin = join(root, "bin");
  const logs = join(root, "logs");
  const defaultWorkspace = join(root, "ws-default");
  const serveDisabledWorkspace = join(root, "ws-serve-disabled");
  for (const dir of [bin, logs, defaultWorkspace, serveDisabledWorkspace]) {
    mkdirSync(dir, { recursive: true });
  }

  const spawnLog = join(logs, "spawn.log");
  const ttyLog = join(logs, "tty.log");
  const fakeCliJs = join(bin, "fake-arcturn.cjs");
  const cliPath = join(bin, "arcturn");

  writeFileSync(fakeCliJs, fakeCliSource(spawnLog, ttyLog));
  // A shell wrapper rather than a shebang: `process.execPath` may contain a
  // space, which a shebang line cannot carry, and `cli.ts` insists on a file
  // it can stat and execute.
  writeFileSync(
    cliPath,
    `#!/bin/sh\nexec ${JSON.stringify(process.execPath)} ${JSON.stringify(fakeCliJs)} "$@"\n`,
  );
  chmodSync(cliPath, 0o755);

  for (const workspace of [defaultWorkspace, serveDisabledWorkspace]) {
    writeFileSync(join(workspace, PLAIN_FILENAME), PROBE_SOURCE);
  }
  writeFileSync(join(defaultWorkspace, QUOTED_FILENAME), PROBE_SOURCE);
  writeFileSync(join(defaultWorkspace, HOSTILE_FILENAME), PROBE_SOURCE);

  // `serve.enabled` is written explicitly in both, rather than left to the
  // manifest default, because test 6 is about what is true *at activation*.
  writeWorkspaceSettings(defaultWorkspace, {
    "arcturn.cliPath": cliPath,
    "arcturn.serve.enabled": true,
    "arcturn.serve.port": 0,
  });
  writeWorkspaceSettings(serveDisabledWorkspace, {
    "arcturn.cliPath": cliPath,
    "arcturn.serve.enabled": false,
  });

  return {
    root,
    cliPath,
    spawnLog,
    ttyLog,
    defaultWorkspace,
    serveDisabledWorkspace,
    /** Per-config profile dirs: a second run must not inherit the first's UI state. */
    profileDir: (label) => join(PROFILE_ROOT, label),
    /**
     * Handed to the extension host so the tests can find the fixture tree.
     *
     * The filenames travel this way rather than being imported: the tests are
     * TypeScript bundled to CJS for mocha, and one shared copy of these strings
     * is worth more than the import would be.
     */
    env: {
      ARCTURN_IT_ROOT: root,
      ARCTURN_IT_CLI: cliPath,
      ARCTURN_IT_SPAWN_LOG: spawnLog,
      ARCTURN_IT_TTY_LOG: ttyLog,
      ARCTURN_IT_WS_DEFAULT: defaultWorkspace,
      ARCTURN_IT_WS_SERVE_DISABLED: serveDisabledWorkspace,
      ARCTURN_IT_FILE_PLAIN: PLAIN_FILENAME,
      ARCTURN_IT_FILE_QUOTED: QUOTED_FILENAME,
      ARCTURN_IT_FILE_HOSTILE: HOSTILE_FILENAME,
      ARCTURN_IT_INJECTION_MARKER: INJECTION_MARKER,
    },
  };
}
