/**
 * OAuth 2.1 client provider for remote (HTTP) MCP servers.
 *
 * The MCP SDK already implements the protocol — PKCE, RFC 9728 protected-
 * resource-metadata discovery, RFC 7591 dynamic client registration, the token
 * exchange and refresh. What it does *not* do is decide where credentials live
 * or how a user is asked to approve the grant. That is what this file supplies:
 * an {@link OAuthClientProvider} whose persistence and user interaction are
 * both injected, so `@arcturn/mcp` stays environment-agnostic (no `fs`, no
 * paths, no browser shelling — the CLI provides those).
 *
 * Security notes that callers must not undo:
 *
 * - The redirect URI is always loopback `127.0.0.1` (RFC 8252 §7.3), never the
 *   string `localhost`, which can resolve to a non-loopback address.
 * - `state` is generated by the caller *before* the authorization URL is built,
 *   so the loopback listener can reject a callback it did not start.
 * - Nothing here logs a token, a code verifier or an authorization URL; the
 *   authorization URL is handed to the injected interaction callback only.
 */

import type { OAuthClientProvider } from "@modelcontextprotocol/sdk/client/auth.js";
import { UnauthorizedError } from "@modelcontextprotocol/sdk/client/auth.js";
import type {
  OAuthClientInformationMixed,
  OAuthClientMetadata,
  OAuthTokens,
} from "@modelcontextprotocol/sdk/shared/auth.js";

/**
 * Redirect URI used when the caller has not bound a loopback listener.
 *
 * A provider built this way can still load and refresh stored credentials; it
 * simply cannot start a new authorization, because
 * {@link McpOAuthProvider.redirectToAuthorization} throws
 * {@link McpAuthRequiredError} without an interaction callback. The value is
 * still a valid loopback URI so a dynamic client registration performed on this
 * path registers something honest.
 */
export const DEFAULT_MCP_REDIRECT_URL = "http://127.0.0.1/callback";

/** Loopback host mandated by RFC 8252 §7.3. Never `localhost`. */
export const MCP_LOOPBACK_HOST = "127.0.0.1";

/** Everything persisted for one OAuth-protected MCP server. */
export interface McpOAuthCredentials {
  /** Access/refresh tokens from the last successful exchange. */
  tokens?: OAuthTokens;
  /** Client id (and secret) from dynamic registration, or pre-registered. */
  clientInformation?: OAuthClientInformationMixed;
  /** PKCE verifier for an authorization in flight. Cleared once exchanged. */
  codeVerifier?: string;
}

/**
 * Persistence seam for {@link McpOAuthProvider}.
 *
 * Implementations own the storage medium and its permissions; the CLI writes
 * one `0600` JSON file per server inside the `0700` `~/.arcturn/auth`
 * directory, and tests use an in-memory record.
 */
export interface McpOAuthStorage {
  /** The stored record, or `undefined` when the server has never been authorized. */
  load(): Promise<McpOAuthCredentials | undefined>;
  /** Replace the stored record. */
  save(credentials: McpOAuthCredentials): Promise<void>;
  /** Remove the stored record. Resolves `false` when nothing was stored. */
  clear(): Promise<boolean>;
}

/** Presents an authorization URL to the user. Must not log it at default verbosity. */
export type McpAuthorizationPrompt = (authorizationUrl: URL) => void | Promise<void>;

/** Options for {@link McpOAuthProvider}. */
export interface McpOAuthProviderOptions {
  /** Configured server name, used only in messages. */
  serverName: string;
  /** Where credentials are read from and written to. */
  storage: McpOAuthStorage;
  /**
   * Loopback redirect URI for this authorization, e.g.
   * `http://127.0.0.1:53219/callback`. Omit when no listener is bound; see
   * {@link DEFAULT_MCP_REDIRECT_URL}.
   */
  redirectUrl?: string;
  /** `state` the callback must echo. Generated by the caller before the URL is built. */
  state?: string;
  /** Scope requested when the server's metadata does not name one. */
  scope?: string;
  /** Client name advertised during dynamic client registration. */
  clientName?: string;
  /**
   * Presents the authorization URL. Absent means non-interactive: a flow that
   * needs the user throws {@link McpAuthRequiredError} instead of hanging.
   */
  prompt?: McpAuthorizationPrompt;
}

/**
 * Thrown when a server needs an interactive authorization that this process
 * cannot run (no TTY, or `--print`).
 *
 * The message names the command that fixes it and never carries a URL, a token
 * or any other authorization parameter, because it is surfaced in `/mcp` status
 * and in warnings.
 */
export class McpAuthRequiredError extends Error {
  /** The configured server name that needs authorization. */
  readonly server: string;

  constructor(server: string) {
    super(
      `MCP server "${server}" requires OAuth authorization. ` + `Run: arcturn mcp auth ${server}`,
    );
    this.name = "McpAuthRequiredError";
    this.server = server;
  }
}

/**
 * True when a failure means "this server needs the user to authorize".
 *
 * Covers both our own {@link McpAuthRequiredError} and the SDK's
 * `UnauthorizedError`, which the HTTP transports throw from `connect`/`send`
 * after a 401 that auth could not resolve.
 */
export function isMcpAuthRequiredError(error: unknown): boolean {
  if (error instanceof McpAuthRequiredError || error instanceof UnauthorizedError) return true;
  if (error instanceof Error) {
    // Transport wrappers occasionally re-throw with the name preserved but the
    // prototype lost across module instances.
    return error.name === "McpAuthRequiredError" || error.name === "UnauthorizedError";
  }
  return false;
}

/** A URL-safe random token, used for `state` when the caller supplies none. */
export function createMcpOAuthState(byteLength = 32): string {
  const bytes = new Uint8Array(byteLength);
  globalThis.crypto.getRandomValues(bytes);
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
}

/**
 * The arcturn-side half of the SDK's OAuth client.
 *
 * Pass an instance as the `authProvider` option of
 * `StreamableHTTPClientTransport`/`SSEClientTransport`, or hand it to the SDK's
 * `auth()` helper to run a standalone authorization.
 */
export class McpOAuthProvider implements OAuthClientProvider {
  readonly #options: McpOAuthProviderOptions;
  #state: string | undefined;

  constructor(options: McpOAuthProviderOptions) {
    this.#options = options;
    this.#state = options.state;
  }

  /** The configured server name this provider authorizes. */
  get serverName(): string {
    return this.#options.serverName;
  }

  get redirectUrl(): string {
    return this.#options.redirectUrl ?? DEFAULT_MCP_REDIRECT_URL;
  }

  get clientMetadata(): OAuthClientMetadata {
    const scope = this.#options.scope;
    return {
      client_name: this.#options.clientName ?? "Arcturn",
      redirect_uris: [this.redirectUrl],
      grant_types: ["authorization_code", "refresh_token"],
      response_types: ["code"],
      // Public client: no secret can be kept on a user's machine, so PKCE is
      // the only proof of possession (OAuth 2.1 §7.5.1).
      token_endpoint_auth_method: "none",
      ...(scope === undefined ? {} : { scope }),
    };
  }

  /** The `state` for this authorization; stable across calls. */
  state(): string {
    this.#state ??= createMcpOAuthState();
    return this.#state;
  }

  async clientInformation(): Promise<OAuthClientInformationMixed | undefined> {
    return (await this.#options.storage.load())?.clientInformation;
  }

  async saveClientInformation(clientInformation: OAuthClientInformationMixed): Promise<void> {
    await this.#merge({ clientInformation });
  }

  async tokens(): Promise<OAuthTokens | undefined> {
    return (await this.#options.storage.load())?.tokens;
  }

  /** Persists tokens, including the ones the SDK mints on a background refresh. */
  async saveTokens(tokens: OAuthTokens): Promise<void> {
    // The verifier belongs to the authorization that just completed; keeping it
    // around would leave a usable secret on disk for no reason.
    await this.#merge({ tokens, codeVerifier: undefined });
  }

  async redirectToAuthorization(authorizationUrl: URL): Promise<void> {
    const prompt = this.#options.prompt;
    if (!prompt) throw new McpAuthRequiredError(this.#options.serverName);
    await prompt(authorizationUrl);
  }

  async saveCodeVerifier(codeVerifier: string): Promise<void> {
    await this.#merge({ codeVerifier });
  }

  async codeVerifier(): Promise<string> {
    const verifier = (await this.#options.storage.load())?.codeVerifier;
    if (verifier === undefined) {
      throw new McpAuthRequiredError(this.#options.serverName);
    }
    return verifier;
  }

  /**
   * Drops credentials the authorization server has rejected, so the SDK can
   * retry cleanly instead of asking the user to delete files by hand.
   */
  async invalidateCredentials(scope: "all" | "client" | "tokens" | "verifier"): Promise<void> {
    if (scope === "all") {
      await this.#options.storage.clear();
      return;
    }
    const current = (await this.#options.storage.load()) ?? {};
    const next: McpOAuthCredentials = { ...current };
    if (scope === "client") delete next.clientInformation;
    if (scope === "tokens") delete next.tokens;
    if (scope === "verifier") delete next.codeVerifier;
    await this.#options.storage.save(next);
  }

  /**
   * Read-modify-write of the stored record.
   *
   * A key present in `patch` with an `undefined` value is a deletion; a key
   * absent from `patch` is left alone. Keeping every field in one record means
   * the token file is rewritten atomically by the storage implementation.
   */
  async #merge(patch: McpOAuthCredentials): Promise<void> {
    const current = (await this.#options.storage.load()) ?? {};
    const next: McpOAuthCredentials = { ...current };
    if ("tokens" in patch) {
      if (patch.tokens === undefined) delete next.tokens;
      else next.tokens = patch.tokens;
    }
    if ("clientInformation" in patch) {
      if (patch.clientInformation === undefined) delete next.clientInformation;
      else next.clientInformation = patch.clientInformation;
    }
    if ("codeVerifier" in patch) {
      if (patch.codeVerifier === undefined) delete next.codeVerifier;
      else next.codeVerifier = patch.codeVerifier;
    }
    await this.#options.storage.save(next);
  }
}

/** An in-memory {@link McpOAuthStorage}; the default for tests. */
export class MemoryMcpOAuthStorage implements McpOAuthStorage {
  #record: McpOAuthCredentials | undefined;

  constructor(initial?: McpOAuthCredentials) {
    this.#record = initial ? structuredClone(initial) : undefined;
  }

  load(): Promise<McpOAuthCredentials | undefined> {
    return Promise.resolve(this.#record ? structuredClone(this.#record) : undefined);
  }

  save(credentials: McpOAuthCredentials): Promise<void> {
    this.#record = structuredClone(credentials);
    return Promise.resolve();
  }

  clear(): Promise<boolean> {
    const had = this.#record !== undefined;
    this.#record = undefined;
    return Promise.resolve(had);
  }
}
